// Static, hand-written articles — no CMS, no markdown lib. Plain content
// blocks rendered by app/blog/[slug]/page.tsx, matching this project's usual
// pattern of local structured data over an external content pipeline (see
// lib/showcase-items.ts for the same approach). IT-only for now (per
// feedback_single_language_dev_workflow) — translate once the tone settles.

export type ContentBlock =
  | { type: "p"; text: string }
  | { type: "h2"; text: string }
  | { type: "ul"; items: string[] }
  | { type: "quote"; text: string; source: string };

export interface BlogPost {
  slug: string;
  title: string;
  excerpt: string;
  category: string;
  publishedAt: string; // ISO date
  readingMinutes: number;
  content: ContentBlock[];
}

export const BLOG_CATEGORIES = ["Colloqui", "CV", "ATS", "LinkedIn", "Carriera"] as const;

export const BLOG_POSTS: BlogPost[] = [
  {
    slug: "colloquio-domande-piu-comuni",
    title: "Le domande più comuni in un colloquio (e come rispondere davvero)",
    excerpt: "\"Parlami di te\" non è una domanda casuale. Ogni domanda da colloquio ne nasconde un'altra, più concreta, che il recruiter non fa ad alta voce.",
    category: "Colloqui",
    publishedAt: "2026-07-02",
    readingMinutes: 5,
    content: [
      { type: "p", text: "Ogni domanda da colloquio ne nasconde un'altra. Quando ti chiedono \"parlami di te\", non vogliono la tua biografia: vogliono capire in 90 secondi se sai raccontare il tuo percorso in modo pertinente al ruolo. Rispondere con l'ordine cronologico delle scuole frequentate è il modo più veloce per perdere l'attenzione di chi ti ascolta." },
      { type: "h2", text: "\"Parlami di te\"" },
      { type: "p", text: "Struttura la risposta in tre parti: dove sei ora professionalmente, come ci sei arrivato in una frase, perché questo ruolo è il passo logico successivo. Novanta secondi, non di più. Se il recruiter vuole sapere di più, farà una domanda di follow-up." },
      { type: "h2", text: "\"Qual è il tuo più grande difetto?\"" },
      { type: "p", text: "La risposta finta (\"sono troppo perfezionista\") si vede a un chilometro di distanza, e chi fa colloqui da anni l'ha sentita centinaia di volte. Scegli un limite vero, di solito legato a un'abitudine di lavoro (delegare poco, sottostimare i tempi, difficoltà a dire no) e racconta cosa hai fatto concretamente per gestirlo. Un esempio specifico vale più di qualsiasi aggettivo." },
      { type: "h2", text: "\"Perché vuoi lasciare il tuo lavoro attuale?\"" },
      { type: "p", text: "Non parlare mai male del capo o dell'azienda precedente, anche se la ragione vera è quella. Sposta il discorso su cosa cerchi, non su cosa fuggi: crescita non disponibile nel ruolo attuale, un cambio di settore che ti interessa da tempo, un progetto che il nuovo ruolo ti permette di seguire. Chi ascolta valuta anche come parli di chi non è nella stanza." },
      { type: "h2", text: "\"Dove ti vedi tra 5 anni?\"" },
      { type: "p", text: "Non serve un piano quinquennale dettagliato. Serve dimostrare che hai un'idea di crescita coerente con quello che l'azienda può offrirti, e che non stai usando questo ruolo come parcheggio in attesa di altro. Se non lo sai con precisione, dillo, ma aggancia la risposta a competenze che vuoi sviluppare, non a titoli di ruolo." },
      { type: "quote", text: "Le domande comportamentali (\"raccontami di una volta in cui...\") si preparano meglio con il metodo STAR: Situazione, Compito, Azione, Risultato. Senza un risultato misurabile alla fine, la storia resta un aneddoto.", source: "Metodo diffuso nella selezione del personale, formalizzato per la prima volta negli anni '70 negli studi sull'intervista comportamentale" },
      { type: "p", text: "Prepara tre episodi della tua carriera che puoi raccontare con il metodo STAR e riadattarli a qualsiasi domanda comportamentale ti facciano. Non serve un episodio diverso per ogni possibile domanda: la stessa storia, raccontata con enfasi diversa, risponde sia a \"parlami di un conflitto in team\" sia a \"parlami di una decisione difficile\"." },
    ],
  },
  {
    slug: "come-superare-filtri-ats",
    title: "Come superare i filtri ATS: cosa legge davvero il software prima del recruiter",
    excerpt: "Un CV bellissimo che l'ATS legge male non arriva mai a un essere umano. Ecco cosa succede davvero dentro il software prima che qualcuno apra il tuo file.",
    category: "ATS",
    publishedAt: "2026-07-09",
    readingMinutes: 6,
    content: [
      { type: "p", text: "La maggior parte delle grandi aziende, e un numero crescente di PMI, usa un ATS (Applicant Tracking System) per raccogliere e filtrare le candidature prima che arrivino a un recruiter umano. Il software non giudica il tuo CV: lo legge, lo trasforma in testo strutturato, e in alcuni casi lo classifica per parole chiave. Un CV che l'ATS legge male, semplicemente, arriva incompleto o non arriva affatto." },
      { type: "h2", text: "Il problema non è il contenuto, è la struttura" },
      { type: "p", text: "Colonne multiple, tabelle, caselle di testo, header e footer con informazioni di contatto: tutti elementi che un occhio umano legge senza sforzo, ma che molti parser ATS leggono da sinistra a destra riga per riga, ignorando la disposizione visiva. Il risultato è testo mescolato: competenze finite in mezzo a un'esperienza lavorativa, il telefono scomparso perché era in un header." },
      { type: "h2", text: "La sidebar è il nemico silenzioso" },
      { type: "p", text: "Il template con foto e colonna laterale (contatti, competenze, lingue) è tra i più diffusi su Canva e Word, ed è anche tra i più rischiosi per un ATS. Non perché la sidebar sia \"vietata\", ma perché il parser spesso legge la pagina per righe orizzontali: il contenuto della colonna stretta finisce intercalato dentro le frasi della colonna larga, e il risultato che arriva al recruiter è illeggibile anche quando il tuo CV originale era perfetto." },
      { type: "h2", text: "Cosa funziona sempre" },
      { type: "ul", items: [
        "Colonna singola, dall'alto verso il basso, senza eccezioni",
        "Titoli di sezione standard: Esperienza, Istruzione, Competenze — non \"Il mio percorso\" o giochi di parole creativi",
        "Testo selezionabile, mai un'immagine o una scansione del CV",
        "Date in un formato coerente in tutto il documento",
        "Parole chiave della job description riprese con lo stesso lessico, non solo sinonimi",
      ] },
      { type: "p", text: "Quest'ultimo punto è quello che la maggior parte delle persone sottovaluta di più. Se l'annuncio cerca \"project management\" e il tuo CV dice solo \"gestione progetti\", un matching per parole chiave esatte può non farli combaciare. Non significa riscrivere il CV copiando l'annuncio parola per parola: significa usare la stessa terminologia quando descrivi cose che hai davvero fatto." },
      { type: "h2", text: "Il test più semplice che puoi fare da solo" },
      { type: "p", text: "Apri il tuo CV, seleziona tutto il testo con Ctrl+A, copialo e incollalo in un editor di testo semplice (non Word: il Blocco Note, o simile). Se quello che vedi è nell'ordine giusto e leggibile, è un buon segno. Se contatti, competenze e bullet di esperienza escono mescolati in un ordine senza senso, quello che vedi tu è più o meno quello che legge anche un ATS." },
    ],
  },
  {
    slug: "cv-una-pagina-o-due",
    title: "CV in una pagina o due? La risposta dipende da questo",
    excerpt: "La regola della pagina unica è utile finché diventa un dogma. Il criterio giusto non è la lunghezza, è la densità di informazione utile per riga.",
    category: "CV",
    publishedAt: "2026-07-16",
    readingMinutes: 4,
    content: [
      { type: "p", text: "\"Il CV deve stare in una pagina\" è uno dei consigli più ripetuti e meno spiegati che esistano. È un buon punto di partenza per chi ha meno di 5 anni di esperienza: a quel livello, due pagine sono quasi sempre un problema di sintesi, non di contenuto reale da mostrare. Oltre i 5-8 anni, però, la regola smette di essere automaticamente vera." },
      { type: "h2", text: "Quando una pagina non basta" },
      { type: "p", text: "Se hai avuto ruoli con responsabilità crescenti, più aziende rilevanti, o un percorso che include un cambio di settore che vale la pena spiegare, comprimere tutto in una pagina spesso significa tagliare proprio i dettagli che dimostrano seniority: i numeri, il contesto del team, la scala del budget gestito. Due pagine ben scritte battono una pagina densa di frasi generiche." },
      { type: "h2", text: "Il criterio giusto: densità, non lunghezza" },
      { type: "p", text: "Ogni riga del CV dovrebbe guadagnarsi il suo posto. Il test è semplice: se togliessi questa riga, il recruiter perderebbe un'informazione che lo aiuta a decidere se convocarti? Se la risposta è no, quella riga va tagliata, indipendentemente da quante pagine restano. Un CV di due pagine dove ogni riga supera questo test è più efficace di un CV di una pagina pieno di paragrafi tirati via." },
      { type: "ul", items: [
        "Esperienze di oltre 10 anni fa: una riga, non un paragrafo, a meno che non siano direttamente rilevanti per il ruolo",
        "Elenchi di competenze software generiche (Pacchetto Office, email): quasi mai utili, occupano spazio senza informare",
        "Descrizioni di mansione senza risultato: se un bullet descrive solo cosa facevi e non cosa hai ottenuto, o lo riscrivi o lo tagli",
      ] },
      { type: "p", text: "Terza pagina, in generale, è quasi sempre troppo, con un'eccezione: i CV accademici o quelli che includono un elenco esteso di pubblicazioni, dove è la convenzione del settore ad aspettarselo. Fuori da quel contesto, tre pagine segnalano che non hai ancora deciso cosa è davvero importante raccontare di te." },
    ],
  },
  {
    slug: "domande-da-fare-al-recruiter",
    title: "Le domande che dovresti fare TU al colloquio",
    excerpt: "\"Non ho domande\" è la risposta che fa più danni in un colloquio. Un buon set di domande finali vale quanto le tue risposte.",
    category: "Colloqui",
    publishedAt: "2026-07-23",
    readingMinutes: 4,
    content: [
      { type: "p", text: "Alla fine di quasi ogni colloquio arriva la stessa domanda: \"hai qualcosa da chiedere a noi?\". Rispondere \"no, penso sia stato tutto chiaro\" è l'equivalente di chiudere un incontro d'affari senza aver capito con chi stai per lavorare. Un colloquio è una valutazione a doppio senso, e le domande che fai raccontano quanto ci hai pensato davvero." },
      { type: "h2", text: "Domande che dimostrano che hai fatto i compiti" },
      { type: "ul", items: [
        "\"Come è cambiato il team negli ultimi 12 mesi, e cosa vi aspettate che cambi nei prossimi 12?\"",
        "\"Qual è la prima cosa concreta che vorreste vedere fatta da chi entra in questo ruolo nei primi 90 giorni?\"",
        "\"Cosa distingue chi ha davvero successo in questo ruolo da chi invece fatica, nella vostra esperienza?\"",
      ] },
      { type: "p", text: "Queste domande fanno due cose insieme: ti danno informazioni reali su cosa ti aspetta, e mostrano a chi ti intervista che stai valutando il ruolo con la stessa serietà con cui loro valutano te." },
      { type: "h2", text: "La domanda che quasi nessuno fa (e dovrebbe)" },
      { type: "p", text: "\"Perché la persona precedente ha lasciato questo ruolo, o perché è stato creato ora?\" È una domanda diretta, non aggressiva se posta con curiosità genuina, e la risposta ti dice moltissimo: turnover alto per un motivo strutturale, crescita del team, un ruolo nuovo di zecca senza precedenti da cui imparare. Ognuna di queste risposte cambia cosa dovresti aspettarti." },
      { type: "h2", text: "Cosa evitare" },
      { type: "p", text: "Non aprire con domande su ferie, smart working o benefit: arriveranno al momento giusto, di solito con HR, e farle troppo presto sposta la percezione da \"persona interessata al ruolo\" a \"persona interessata alle condizioni\". Non è sbagliato chiederle, è sbagliato il momento." },
    ],
  },
  {
    slug: "ottimizzare-profilo-linkedin",
    title: "Come ottimizzare il profilo LinkedIn per farti trovare (non solo per farti vedere)",
    excerpt: "Un profilo LinkedIn curato ma invisibile alla ricerca non serve a molto. La differenza è tra scrivere per chi legge e scrivere per chi cerca.",
    category: "LinkedIn",
    publishedAt: "2026-07-30",
    readingMinutes: 5,
    content: [
      { type: "p", text: "Molti profili LinkedIn sono scritti bene per chi li legge e quasi invisibili per chi cerca. Sono due cose diverse. I recruiter, quando cercano candidati attivamente, filtrano per parole chiave specifiche in un motore di ricerca interno: se il tuo titolo è \"Problem solver appassionato di persone\" invece di \"Customer Success Manager\", semplicemente non comparirai in quella ricerca, per quanto il tuo profilo sia scritto bene." },
      { type: "h2", text: "Il titolo (headline) è la riga più importante che hai" },
      { type: "p", text: "Di default LinkedIn usa il tuo ruolo attuale come titolo. È uno spreco: quello spazio dovrebbe contenere il ruolo che cerchi, 2-3 competenze chiave verificabili, e un settore o dominio specifico. \"Senior Product Manager | SaaS B2B | Go-to-Market e Pricing Strategy\" fa il lavoro di ricerca al posto del recruiter." },
      { type: "h2", text: "Il riepilogo non è una biografia" },
      { type: "p", text: "La sezione \"Informazioni\" non serve a raccontare la tua vita, serve a rispondere in 3-4 righe alla domanda \"perché dovrei contattare questa persona per un ruolo aperto\". Le prime due righe sono quelle che si vedono senza cliccare \"vedi altro\": mettici il contenuto più forte, non l'introduzione." },
      { type: "h2", text: "Le competenze contano solo se qualcuno le conferma" },
      { type: "p", text: "Una lista di 40 competenze senza nessuna conferma pesa meno di 8 competenze con conferme reali da colleghi o manager. LinkedIn dà peso, nella ricerca interna, alle competenze più confermate del tuo profilo: se le prime tre in elenco sono generiche e senza conferme, riordina manualmente mettendo davanti quelle più specifiche e più validate." },
      { type: "h2", text: "Attività, non solo presenza" },
      { type: "p", text: "Un profilo statico, aggiornato una volta e mai più toccato, tende a perdere visibilità nell'algoritmo di ricerca nel tempo rispetto a profili con attività regolare (commenti, articoli, aggiornamenti). Non serve pubblicare ogni giorno: basta un'interazione genuina ogni tanto su contenuti del proprio settore, che è anche il modo più naturale per restare visibile alla propria rete senza sembrare in cerca disperata di lavoro." },
    ],
  },
  {
    slug: "errori-cv-che-scartano-candidatura",
    title: "5 errori nel CV che fanno scartare una candidatura in pochi secondi",
    excerpt: "Uno studio di eye-tracking spesso citato parla di circa 6 secondi di prima occhiata. In quel tempo, alcuni errori pesano più di altri.",
    category: "CV",
    publishedAt: "2026-08-06",
    readingMinutes: 5,
    content: [
      { type: "quote", text: "Uno studio di eye-tracking del 2012 di TheLadders, spesso citato (e talvolta semplificato) nel settore HR, ha misurato un tempo medio di prima occhiata su un CV di circa 6 secondi prima che il recruiter decidesse se continuare a leggere.", source: "TheLadders, \"Eye-Tracking Study\", 2012 — cifra ampiamente ripresa nella letteratura di settore, da prendere come ordine di grandezza più che come dato scientifico definitivo" },
      { type: "p", text: "Sei secondi non bastano per leggere un CV, bastano per farsi un'impressione. In quel lasso di tempo alcuni errori pesano più di altri, perché saltano all'occhio prima ancora di leggere una singola parola." },
      { type: "h2", text: "1. Bio generica in apertura" },
      { type: "p", text: "\"Professionista motivato e dinamico con forte spirito di squadra\" non dice nulla a nessuno: potrebbe essere scritta da chiunque, per qualsiasi ruolo. Le prime due righe del CV dovrebbero contenere il tuo ruolo attuale, un numero o un risultato concreto, e il tipo di ruolo che cerchi. Zero aggettivi che non si possono verificare." },
      { type: "h2", text: "2. Bullet senza numeri" },
      { type: "p", text: "\"Gestione del team di vendita\" descrive un compito. \"Gestito un team di 8 persone, superando il target trimestrale del 15% per 4 trimestri consecutivi\" descrive un risultato. Non ogni bullet può avere un numero perfetto, ma se in tutto il CV non ce n'è nemmeno uno, è un segnale che salta all'occhio in pochi secondi anche a chi non legge riga per riga." },
      { type: "h2", text: "3. Un layout che nasconde le informazioni chiave" },
      { type: "p", text: "Foto grande, colonna laterale decorativa, tre font diversi: nessuno di questi elementi aiuta un recruiter a trovare in fretta ruolo, azienda e date. Se il layout richiede uno sforzo per orientarsi, quello sforzo viene sottratto al tempo che il recruiter avrebbe dedicato a leggere davvero cosa hai fatto." },
      { type: "h2", text: "4. Refusi ed errori di battitura" },
      { type: "p", text: "Un refuso isolato capita a chiunque e raramente costa una candidatura da solo. Più refusi nello stesso documento, però, vengono letti come un segnale di scarsa attenzione ai dettagli, ancora di più se il ruolo richiede precisione (contabilità, editing, legale). Rileggere il CV ad alta voce, non solo a schermo, aiuta a intercettare errori che l'occhio salta per abitudine." },
      { type: "h2", text: "5. Contatti sbagliati o difficili da trovare" },
      { type: "p", text: "Sembra ovvio, eppure capita: un numero di telefono con una cifra sbagliata, un indirizzo email di lavoro precedente ancora attivo nel documento, contatti infilati in un header che alcuni software non leggono correttamente. Controlla che chiamando il numero e scrivendo all'email risponda davvero qualcuno, cioè te." },
    ],
  },
  {
    slug: "spiegare-buco-cv-cambio-carriera",
    title: "Come spiegare un buco nel CV o un cambio di carriera senza giustificarti",
    excerpt: "Un periodo vuoto nel CV non è un problema da nascondere, è un fatto da inquadrare. La differenza tra i due approcci si sente subito in colloquio.",
    category: "Carriera",
    publishedAt: "2026-08-13",
    readingMinutes: 5,
    content: [
      { type: "p", text: "Un periodo senza lavoro, o un cambio di settore che non segue una logica lineare, non è automaticamente un problema per un recruiter. Diventa un problema quando la persona che lo racconta sembra doversi giustificare, invece di inquadrare semplicemente cosa è successo e cosa ne ha portato con sé." },
      { type: "h2", text: "Nel CV: non nascondere le date, contestualizzale" },
      { type: "p", text: "Sparire per mesi o anni da un CV senza spiegazione genera più sospetto di un periodo dichiarato con chiarezza. Se in quel periodo hai fatto formazione, freelance, volontariato o ti sei preso cura di un famigliare, una riga basta: \"2023-2024 — Percorso di certificazione in [ambito] e collaborazioni freelance\". Non serve un paragrafo di scuse, serve una riga che riempie il vuoto con un fatto." },
      { type: "h2", text: "In colloquio: il tono conta più delle parole" },
      { type: "p", text: "Le stesse informazioni, dette con tono difensivo o con tono neutro, arrivano in modo completamente diverso. \"Purtroppo ho dovuto lasciare il lavoro per motivi personali\" suona come una scusa. \"Ho preso una pausa per motivi personali, e l'ho usata anche per [attività concreta]\" suona come una scelta di cui hai il controllo. Il contenuto può essere identico: cambia solo l'inquadramento." },
      { type: "h2", text: "Cambio di carriera: la connessione conta più della coerenza formale" },
      { type: "p", text: "Un percorso da avvocato a project manager, o da insegnante a UX designer, non ha bisogno di sembrare un percorso lineare per essere convincente. Ha bisogno di una connessione esplicita: quali competenze del ruolo precedente si trasferiscono davvero al nuovo (gestione di stakeholder, comunicazione complessa, organizzazione di progetti con scadenze rigide), dette con esempi specifici, non con un generico \"le competenze trasversali\"." },
      { type: "p", text: "Chi fa selezione ha visto decine di cambi di carriera diversi. Quello che nota, in positivo o in negativo, è se la persona davanti a sé ha già fatto la fatica di collegare i punti, o se si aspetta che sia il recruiter a farlo per lei." },
    ],
  },
  {
    slug: "lettera-presentazione-serve-ancora",
    title: "La lettera di presentazione serve ancora nel 2026?",
    excerpt: "Dipende da chi la legge e da come è scritta. Una lettera copiata dal CV non serve a nessuno, una scritta bene può ancora fare la differenza.",
    category: "CV",
    publishedAt: "2026-08-18",
    readingMinutes: 4,
    content: [
      { type: "p", text: "Dipende. Alcune aziende non la leggono mai, altre la considerano un vero e proprio filtro di selezione, soprattutto per ruoli dove la scrittura conta (comunicazione, marketing, contenuti, alcuni ruoli in ambito legale). Quello che è certo è che una lettera che ripete il CV con frasi più lunghe non aggiunge nulla, e in alcuni casi toglie punti invece di aggiungerne." },
      { type: "h2", text: "Quando scriverla ha senso" },
      { type: "ul", items: [
        "Quando l'annuncio la richiede esplicitamente: non scriverla, in quel caso, è un segnale negativo",
        "Quando devi spiegare qualcosa che il CV da solo non chiarisce (un cambio di settore, un rientro dopo una pausa)",
        "Quando candidarti per un'azienda specifica per cui hai una motivazione reale e concreta, non generica",
      ] },
      { type: "h2", text: "Cosa deve fare una buona lettera (e cosa non deve fare)" },
      { type: "p", text: "Non deve riassumere il CV. Deve rispondere a una domanda che il CV da solo non può: perché questa azienda, perché ora, e cosa porti che altri candidati con un profilo simile non porterebbero. Tre paragrafi bastano quasi sempre: un'apertura diretta che nomina il ruolo e l'azienda, un corpo che collega una o due esperienze concrete al problema che l'azienda sta cercando di risolvere, una chiusura breve senza supplicare." },
      { type: "h2", text: "L'errore più comune: scriverla generica e riciclarla per ogni candidatura" },
      { type: "p", text: "Una lettera che potrebbe essere inviata a qualsiasi azienda dello stesso settore, cambiando solo il nome in cima, si vede a colpo d'occhio, e vale meno di zero: comunica che non hai dedicato tempo a quella candidatura specifica. Se non hai tempo per personalizzarla almeno in parte, spesso è meglio non scriverla affatto, quando non è obbligatoria." },
    ],
  },
  {
    slug: "negoziare-stipendio-dopo-offerta",
    title: "Come negoziare lo stipendio dopo aver ricevuto un'offerta",
    excerpt: "La maggior parte delle offerte iniziali ha un margine di negoziazione. Il problema non è chiedere, è come e quando farlo.",
    category: "Carriera",
    publishedAt: "2026-08-20",
    readingMinutes: 5,
    content: [
      { type: "p", text: "La maggior parte delle prime offerte lascia un margine di trattativa: le aziende raramente aprono con la cifra massima disponibile per il ruolo. Il problema non è se negoziare, ma come farlo senza compromettere un'offerta che, a conti fatti, potrebbe già essere buona." },
      { type: "h2", text: "Prima regola: mai il primo numero" },
      { type: "p", text: "Se ti chiedono le tue aspettative economiche prima ancora di ricevere un'offerta, evita di sparare un numero secco. Rispondi con un range basato su ricerche reali di mercato per quel ruolo, quella seniority, quella zona geografica, e aggiungi che sei aperto a discuterne in base al pacchetto completo. Chi fa la prima offerta, in una trattativa, parte quasi sempre svantaggiato." },
      { type: "h2", text: "Quando arriva l'offerta: non rispondere subito" },
      { type: "p", text: "Anche se la cifra ti sembra già ottima, prenditi 24-48 ore prima di rispondere. Non per finta strategia, ma perché una risposta immediata ed entusiasta toglie qualsiasi leva per chiedere qualcosa in più: bonus di ingresso, giorni di ferie aggiuntivi, una data di revisione salariale anticipata a 6 mesi invece che a 12." },
      { type: "h2", text: "Come formulare la controproposta" },
      { type: "p", text: "Ringrazia per l'offerta, conferma l'interesse reale per il ruolo, poi chiedi la cifra specifica motivandola con dati concreti: altre offerte in corso (se vere), ricerche di mercato, o competenze specifiche che il ruolo richiede e che porti già pronte all'uso. \"Vorrei X\" senza motivazione è una richiesta debole. \"Vorrei X, in linea con [dato di mercato] per ruoli equivalenti nella zona\" è una richiesta che si può discutere seriamente." },
      { type: "h2", text: "Cosa negoziare oltre allo stipendio base" },
      { type: "ul", items: [
        "Bonus di ingresso una tantum, spesso più facile da ottenere di un aumento sul fisso",
        "Data della prima revisione salariale (chiedere 6 mesi invece di 12 è una richiesta ragionevole)",
        "Giorni di ferie aggiuntivi o flessibilità di orario/smart working",
        "Budget formazione o certificazioni pagate dall'azienda",
      ] },
      { type: "p", text: "Un'ultima cosa da tenere a mente: un'azienda seria non ritira un'offerta perché hai chiesto, con educazione e con dati alla mano, di discutere le condizioni. Se succede, è un'informazione preziosa su che tipo di ambiente di lavoro stavi per accettare." },
    ],
  },
  {
    slug: "colloquio-da-remoto-video",
    title: "Come affrontare un colloquio video senza sembrare impacciato",
    excerpt: "Un colloquio in videochiamata non è un colloquio in presenza spostato su schermo. Cambiano le regole di attenzione, di sguardo, di silenzio.",
    category: "Colloqui",
    publishedAt: "2026-04-24",
    readingMinutes: 4,
    content: [
      { type: "p", text: "Un colloquio video non è la versione digitale di un colloquio in presenza. Alcune cose che funzionano di persona (una pausa lunga per pensare, un gesto delle mani, la lettura del linguaggio del corpo) funzionano peggio o non funzionano affatto attraverso una webcam. Trattarlo come identico è il primo errore." },
      { type: "h2", text: "Guarda la camera, non lo schermo" },
      { type: "p", text: "Sembra un dettaglio tecnico, ma è quello che decide se sembri presente o distratto. Guardare il volto dell'interlocutore sullo schermo, invece dell'obiettivo della webcam, dà a chi ti guarda la sensazione che tu stia leggendo qualcosa o guardando altrove. Metti una nota adesiva vicino alla camera se ti aiuta a ricordartelo nei primi minuti, finché non diventa automatico." },
      { type: "h2", text: "L'audio conta più del video" },
      { type: "p", text: "Un video leggermente sgranato si perdona, un audio che si interrompe o rimbomba no: costringe l'altra persona a chiedere di ripetere, e ogni ripetizione toglie fluidità alla conversazione. Cuffie con microfono, anche economiche, valgono più di una webcam costosa. Testa la connessione qualche minuto prima, non all'ora esatta del colloquio." },
      { type: "h2", text: "Il silenzio pesa di più online" },
      { type: "p", text: "In presenza, una pausa di 3 secondi per pensare è normale. In video, la stessa pausa sembra più lunga per via della latenza e dell'assenza dei segnali non verbali che normalmente colmano il vuoto. Se ti serve un attimo, dillo: \"Fammi pensare un secondo\" funziona meglio di un silenzio che l'altra persona non sa come interpretare." },
      { type: "h2", text: "Prepara l'ambiente come prepareresti un vestito" },
      { type: "ul", items: [
        "Sfondo neutro, senza persone che passano dietro di te",
        "Luce davanti al viso, mai alle spalle (altrimenti resti in controluce)",
        "Notifiche del telefono e del computer disattivate per tutta la durata",
        "Un bicchiere d'acqua a portata di mano, fuori dall'inquadratura",
      ] },
      { type: "p", text: "Nessuno di questi dettagli, da solo, decide un'assunzione. Insieme, tolgono attrito da una conversazione che ha già abbastanza variabili di cui preoccuparsi." },
    ],
  },
  {
    slug: "descrivere-risultati-senza-numeri",
    title: "Come raccontare risultati concreti quando il tuo ruolo non produce numeri facili",
    excerpt: "\"Aumentato le vendite del 30%\" funziona per chi vende. Per chi lavora in ruoli di supporto, cura o back-office, il risultato si misura diversamente.",
    category: "CV",
    publishedAt: "2026-05-01",
    readingMinutes: 5,
    content: [
      { type: "p", text: "Il consiglio \"metti sempre un numero nei bullet\" funziona benissimo per chi lavora in vendita, marketing o operations, dove i numeri sono la lingua nativa del ruolo. Per chi lavora in ruoli educativi, sanitari, amministrativi o di supporto, applicarlo alla lettera porta spesso a inventare percentuali poco credibili solo per riempire lo schema." },
      { type: "h2", text: "Il numero non è sempre una percentuale di fatturato" },
      { type: "p", text: "Volume, scala e frequenza sono forme di misura valide quanto una percentuale: quante persone hai gestito o formato, quanti casi hai seguito in parallelo, con quale cadenza, su che arco di tempo. \"Seguito 40 famiglie in carico sociale contemporaneamente, con un tasso di chiusura positiva dei casi dell'80%\" è un numero vero anche se non parla di soldi." },
      { type: "h2", text: "Quando il numero davvero non esiste" },
      { type: "p", text: "Per alcuni ruoli, forzare un numero significa inventarlo. In quei casi, il sostituto migliore è il contesto specifico: non \"gestito situazioni complesse\", ma \"gestito la comunicazione con famiglie in situazioni di crisi acuta, coordinandomi con servizi sociali ed enti esterni\". La specificità del contesto fa lo stesso lavoro persuasivo di un numero: dimostra che hai fatto davvero quella cosa, non che l'hai solo elencata." },
      { type: "h2", text: "Il prima/dopo funziona senza percentuali" },
      { type: "p", text: "\"Ho ereditato un archivio cartaceo disorganizzato e ho costruito un sistema digitale usato ancora oggi da tutto l'ufficio\" descrive un cambiamento di stato, prima e dopo, senza una sola cifra. È una struttura che funziona per quasi ogni ruolo, anche i più lontani dal linguaggio commerciale: cosa c'era prima che tu arrivassi, cosa c'è ora, e cosa hai fatto tu perché cambiasse." },
    ],
  },
  {
    slug: "parole-chiave-annuncio-lavoro",
    title: "Come leggere un annuncio di lavoro per trovare le parole chiave giuste",
    excerpt: "Copiare un annuncio parola per parola nel CV si vede, e non funziona. Leggerlo bene per estrarre il linguaggio giusto è un'altra cosa.",
    category: "ATS",
    publishedAt: "2026-05-08",
    readingMinutes: 4,
    content: [
      { type: "p", text: "\"Usa le parole chiave dell'annuncio\" è un consiglio giusto applicato male molto spesso. Copiare frasi intere dall'annuncio dentro il CV si nota, sembra artificiale, e in alcuni casi può risultare controproducente se chi legge fa il confronto diretto. Il lavoro utile è un altro: capire quali termini sono davvero centrali nell'annuncio, e verificare se il tuo CV li usa quando descrivi cose che hai realmente fatto." },
      { type: "h2", text: "Non tutte le parole dell'annuncio pesano uguale" },
      { type: "p", text: "In un annuncio, alcune parole sono requisiti reali (\"esperienza con SQL\", \"gestione di team internazionali\"), altre sono riempitivo aziendale (\"ambiente dinamico\", \"cultura orientata ai risultati\"). Un ATS che filtra per parole chiave cerca soprattutto le prime, i requisiti concreti, non lo stile comunicativo dell'annuncio." },
      { type: "h2", text: "Il metodo delle tre letture" },
      { type: "ul", items: [
        "Prima lettura: sottolinea ogni competenza tecnica o strumento nominato esplicitamente",
        "Seconda lettura: sottolinea i verbi d'azione ricorrenti (gestire, coordinare, analizzare, sviluppare)",
        "Terza lettura: confronta le due liste con il tuo CV attuale, e nota dove usi un sinonimo invece del termine esatto usato nell'annuncio",
      ] },
      { type: "p", text: "Se l'annuncio dice \"project management\" e tu hai scritto \"gestione di progetti\", non stai mentendo, ma stai rischiando che un matching automatico per termine esatto non li consideri equivalenti. La correzione non è riscrivere tutto il CV, è adattare la formulazione di quella specifica riga, mantenendo il fatto reale che descrive." },
      { type: "h2", text: "Il segnale di un annuncio da evitare" },
      { type: "p", text: "Un annuncio che elenca 25 competenze diverse come \"richieste\" per uno stesso ruolo, spesso, è scritto in fretta o descrive un ruolo mal definito internamente. Non è colpa tua se non le hai tutte: in molti casi, chi assume per davvero valuta 4 o 5 di quelle 25 come effettivamente decisive." },
    ],
  },
  {
    slug: "messaggio-networking-linkedin-che-funziona",
    title: "Come scrivere un messaggio di networking su LinkedIn che ottiene risposta",
    excerpt: "\"Ciao, vorrei entrare in contatto\" ha un tasso di risposta bassissimo. La differenza è chiedere qualcosa di piccolo e specifico, non tutto e subito.",
    category: "LinkedIn",
    publishedAt: "2026-05-15",
    readingMinutes: 4,
    content: [
      { type: "p", text: "La maggior parte dei messaggi di networking su LinkedIn fallisce per lo stesso motivo: chiedono troppo, troppo presto, a una persona che non ti conosce. \"Ciao, mi piacerebbe fare due chiacchiere sulla tua azienda\" è una richiesta vaga, che costa tempo a chi la riceve senza dargli un motivo chiaro per accettare." },
      { type: "h2", text: "Chiedi una cosa piccola, non un favore grande" },
      { type: "p", text: "\"15 minuti al telefono\" è un impegno percepito come alto da chi non ti conosce. Una domanda specifica a cui si può rispondere per iscritto in due righe (\"Come è strutturato il team di prodotto nella tua azienda?\") ha un tasso di risposta molto più alto, e spesso apre comunque la porta a una conversazione più lunga se la persona è disponibile." },
      { type: "h2", text: "Il messaggio che funziona ha una struttura precisa" },
      { type: "ul", items: [
        "Una riga su chi sei e perché scrivi a questa persona specifica (non un template generico)",
        "Una riga sul motivo del contatto, concreto e limitato nel tempo che chiedi",
        "Una domanda chiusa e specifica, non \"possiamo sentirci\"",
      ] },
      { type: "p", text: "\"Ciao [Nome], ho visto che lavori come [ruolo] in [azienda] e sto valutando un passaggio simile dopo [contesto breve]. Avresti 2 minuti per dirmi se nella tua esperienza il ruolo di [X] richiede più [competenza A] o più [competenza B]?\" è più lungo di \"vorrei entrare in contatto\", ma costa molto meno a chi lo riceve." },
      { type: "h2", text: "Il follow-up conta quanto il primo messaggio" },
      { type: "p", text: "Molte persone non rispondono al primo messaggio semplicemente perché lo perdono tra le notifiche, non per disinteresse. Un secondo messaggio breve dopo una settimana (\"Capisco che sei impegnato, giusto un piccolo promemoria\") recupera una parte non trascurabile di risposte che altrimenti si perderebbero." },
    ],
  },
  {
    slug: "accettare-offerta-lavoro-checklist",
    title: "Come decidere se accettare un'offerta di lavoro: una checklist oltre lo stipendio",
    excerpt: "Lo stipendio è la prima cosa che si guarda e spesso l'unica su cui si decide. Alcune domande che contano altrettanto restano senza risposta.",
    category: "Carriera",
    publishedAt: "2026-05-22",
    readingMinutes: 5,
    content: [
      { type: "p", text: "Di fronte a un'offerta buona, è facile fermarsi alla cifra e dire sì. Alcune delle cause più comuni di insoddisfazione nei primi mesi di un nuovo lavoro, però, non hanno nulla a che vedere con lo stipendio: riguardano il manager diretto, il ritmo reale del lavoro, o quanto il ruolo descritto in colloquio corrisponde a quello vissuto ogni giorno." },
      { type: "h2", text: "Chi sarà il tuo manager diretto, non l'azienda in astratto" },
      { type: "p", text: "Si valuta l'azienda, la sua reputazione, i suoi valori dichiarati, ma si lavora ogni giorno con una persona specifica: il manager diretto. Se durante il processo di selezione non hai mai parlato direttamente con chi sarà il tuo responsabile, è una domanda legittima da fare prima di accettare, non dopo." },
      { type: "h2", text: "Cosa succede davvero nei primi 90 giorni" },
      { type: "p", text: "Un'offerta che descrive il ruolo in termini generali (\"contribuirai alla crescita del team\") lascia aperta una domanda pratica: cosa farai letteralmente, giorno per giorno, nel primo trimestre? Se questa domanda non ha una risposta chiara nemmeno dopo averla fatta esplicitamente, è un segnale che il ruolo potrebbe non essere ancora ben definito internamente." },
      { type: "h2", text: "La lista delle domande da farti prima di rispondere" },
      { type: "ul", items: [
        "Il pacchetto completo (bonus, ferie, benefit) è competitivo quanto la cifra base?",
        "Il tempo di spostamento casa-lavoro o le condizioni di smart working sono sostenibili nel tempo, non solo accettabili per ora?",
        "C'è un percorso di crescita dichiarato, o il ruolo rischia di restare identico tra 2 anni?",
        "Il turnover recente in quel team è normale o segnala un problema strutturale?",
      ] },
      { type: "p", text: "Nessuna di queste domande ha una risposta giusta universale. Hanno un peso diverso per persone diverse, in momenti diversi della carriera. Il problema non è quale risposta dai, è non esserti nemmeno fatto la domanda prima di firmare." },
    ],
  },
  {
    slug: "colloquio-di-gruppo-assessment-center",
    title: "Colloquio di gruppo e assessment center: come funzionano davvero",
    excerpt: "Un assessment center non valuta solo cosa dici, valuta come ti comporti quando altri candidati stanno cercando di emergere nella stessa stanza.",
    category: "Colloqui",
    publishedAt: "2026-05-29",
    readingMinutes: 5,
    content: [
      { type: "p", text: "Gli assessment center, usati soprattutto nei processi di selezione per grandi aziende e programmi graduate, mettono più candidati nella stessa stanza a lavorare su un caso o un'attività condivisa. Non valutano solo la qualità delle idee: valutano il comportamento in un contesto di competizione visibile, cosa che un colloquio individuale non può misurare." },
      { type: "h2", text: "Cosa osservano davvero i valutatori" },
      { type: "p", text: "Non chi parla di più, ma chi fa avanzare la discussione. Un candidato che interrompe continuamente per imporre la propria idea viene letto come scarsamente collaborativo, tanto quanto uno che resta in silenzio per tutta la durata dell'esercizio viene letto come poco propositivo. Il profilo che emerge meglio, quasi sempre, è chi ascolta, costruisce sulle idee altrui, e sa anche prendere una decisione quando il gruppo si blocca." },
      { type: "h2", text: "Ruoli che aiutano a farsi notare senza prevaricare" },
      { type: "ul", items: [
        "Chi tiene traccia del tempo e richiama il gruppo all'obiettivo quando la discussione si disperde",
        "Chi fa da sintesi a metà esercizio, riassumendo cosa è stato deciso finora",
        "Chi coinvolge esplicitamente chi non ha ancora parlato (\"tu cosa ne pensi?\")",
      ] },
      { type: "p", text: "Nessuno di questi ruoli richiede di essere il più brillante della stanza. Richiedono di essere la persona che fa funzionare meglio il gruppo, che è esattamente quello che molte aziende cercano di misurare con questo formato." },
      { type: "h2", text: "L'errore più comune: trattarlo come una gara individuale" },
      { type: "p", text: "Alcuni candidati arrivano preparati a \"vincere\" la discussione, dimenticando che il gruppo intero viene osservato insieme. Un'idea proposta con forza ma mai messa in discussione, in un esercizio che dura 30-40 minuti, si nota come un segnale di scarso ascolto, indipendentemente da quanto l'idea fosse effettivamente buona." },
    ],
  },
  {
    slug: "referenze-lavorative-quando-servono",
    title: "Referenze lavorative: quando servono davvero e come gestirle",
    excerpt: "Non ogni processo di selezione le chiede, ma quando lo fa, farsi trovare impreparati costa più di quanto sembri.",
    category: "CV",
    publishedAt: "2026-06-05",
    readingMinutes: 4,
    content: [
      { type: "p", text: "Le referenze lavorative non sono richieste in ogni processo di selezione, ma quando lo sono, di solito arrivano nella fase finale, dopo che l'azienda ha già deciso che vuole assumerti. Proprio per questo, una gestione confusa delle referenze in quel momento può rallentare o compromettere un'offerta quasi certa." },
      { type: "h2", text: "Non mettere \"referenze disponibili su richiesta\" nel CV" },
      { type: "p", text: "È una frase che non aggiunge informazione: se servono, te le chiederanno comunque. Occupa spazio nel CV senza dire nulla di verificabile, ed è considerata da molti recruiter un riempitivo datato più che un'informazione utile." },
      { type: "h2", text: "Scegli le persone giuste, non solo quelle disponibili" },
      { type: "p", text: "Un ex manager diretto che può parlare del tuo lavoro quotidiano vale più di un dirigente di alto livello che ti conosceva solo di vista. Chi chiama per una referenza cerca dettagli concreti sul tuo modo di lavorare, non un endorsement generico da parte di un nome altisonante." },
      { type: "h2", text: "Avvisa sempre prima, senza eccezioni" },
      { type: "p", text: "Dare il contatto di qualcuno senza avvisarlo prima è un rischio doppio: la persona potrebbe rispondere in modo distratto o impreparato a una chiamata inattesa, e potrebbe anche risentirsi di essere stata coinvolta senza permesso. Un messaggio breve prima di ogni processo di selezione avanzato (\"potrebbero contattarti nei prossimi giorni per una referenza su di me, va bene?\") evita entrambi i problemi." },
      { type: "h2", text: "Prepara le tue referenze come prepari te stesso" },
      { type: "p", text: "Se sai che una referenza sta per essere contattata, condividi con quella persona il ruolo specifico per cui ti stai candidando e 2-3 punti che vorresti emergessero, senza scriverle un copione. Una referenza allineata con quello che hai raccontato tu in colloquio rafforza la tua candidatura; una referenza che racconta una versione diversa, anche in buona fede, la indebolisce." },
    ],
  },
  {
    slug: "dare-le-dimissioni-senza-bruciare-ponti",
    title: "Come dare le dimissioni senza bruciare ponti",
    excerpt: "Il mondo del lavoro, in molti settori, è più piccolo di quanto sembri. Come te ne vai da un'azienda conta quanto come ci sei entrato.",
    category: "Carriera",
    publishedAt: "2026-06-12",
    readingMinutes: 4,
    content: [
      { type: "p", text: "In molti settori, soprattutto quelli più verticali o locali, le persone si rincontrano: un ex collega diventa cliente, un ex manager diventa referenza per il lavoro successivo. Come lasci un'azienda ha un peso reale sulla tua reputazione professionale, indipendentemente da quanto il rapporto si sia deteriorato negli ultimi mesi." },
      { type: "h2", text: "Comunica prima al tuo manager diretto, sempre" },
      { type: "p", text: "Che il tuo manager lo scopra da un collega, da un post su LinkedIn o da un'email diffusa prima ancora di una conversazione diretta è uno degli errori più difficili da recuperare. Anche se il rapporto non è ottimo, la comunicazione diretta e personale prima di qualsiasi annuncio pubblico è un segno minimo di rispetto professionale che viene ricordato a lungo." },
      { type: "h2", text: "Il periodo di preavviso non è tempo morto" },
      { type: "p", text: "Le ultime settimane in un'azienda sono spesso vissute con il pilota automatico, ma sono anche l'ultima impressione concreta che lasci. Documentare il proprio lavoro, passare le consegne con cura, restare disponibile per domande dopo l'uscita: sono gesti piccoli che restano nella memoria molto più a lungo del contenuto specifico del lavoro fatto in quelle settimane." },
      { type: "h2", text: "Non serve spiegare tutto, ma quello che dici deve essere vero" },
      { type: "p", text: "Non sei obbligato a raccontare il motivo reale e completo delle tue dimissioni a tutti in azienda. Sei obbligato, per la tua stessa credibilità futura, a non raccontare qualcosa di falso che potrebbe essere smentito in seguito. \"Ho ricevuto un'opportunità che voglio esplorare\" è vero e sufficiente anche quando il motivo reale è più complicato." },
      { type: "h2", text: "Il colloquio di uscita è ancora un colloquio" },
      { type: "p", text: "Se l'azienda propone un colloquio di uscita (exit interview), trattalo con la stessa cura di un colloquio normale: onestà utile, non sfogo. Un feedback costruttivo su un problema reale, detto con calma, ha più peso e lascia un ricordo migliore di un elenco di lamentele accumulate negli anni." },
    ],
  },
  {
    slug: "email-di-ringraziamento-dopo-colloquio",
    title: "L'email di follow-up dopo un colloquio: cosa scrivere (e quando)",
    excerpt: "Non decide da sola un'assunzione, ma la sua assenza si nota più di quanto si pensi, soprattutto a parità di altri candidati validi.",
    category: "Colloqui",
    publishedAt: "2026-06-19",
    readingMinutes: 3,
    content: [
      { type: "p", text: "Un'email di follow-up dopo un colloquio non ribalta una candidatura debole, ma a parità di altri fattori può fare la differenza tra due candidati validi. Il motivo non è magico: dimostra attenzione e reale interesse, due cose che un colloquio da solo non sempre riesce a comunicare del tutto." },
      { type: "h2", text: "Quando inviarla" },
      { type: "p", text: "Entro 24 ore dal colloquio, idealmente la sera stessa o la mattina dopo. Oltre le 48 ore, l'effetto si affievolisce: il ricordo del colloquio nella mente di chi ti ha intervistato è già meno vivido, e l'email rischia di sembrare un ripensamento tardivo più che un gesto naturale." },
      { type: "h2", text: "Cosa deve contenere (ed essere breve)" },
      { type: "ul", items: [
        "Un ringraziamento specifico per il tempo dedicato, non generico",
        "Un riferimento concreto a un punto discusso nel colloquio, che dimostri che hai ascoltato davvero",
        "Una riga che rinnova l'interesse per il ruolo, senza supplicare",
      ] },
      { type: "p", text: "\"Grazie per il tempo di oggi, in particolare per aver approfondito come gestite [progetto specifico menzionato]: mi ha confermato quanto il ruolo sia allineato con quello che cerco\" fa il lavoro in tre righe. Non serve un paragrafo lungo, e non serve ripetere il tuo intero background: quello lo ha già in mano chi ti ha intervistato." },
      { type: "h2", text: "Se il colloquio è andato con più persone" },
      { type: "p", text: "Un'email identica copiata e incollata a più interlocutori diversi si nota facilmente se confrontano le email tra loro, cosa che succede più spesso di quanto si pensi. Personalizza almeno una riga per ciascuna persona, agganciata a qualcosa di specifico di cui avete parlato solo con lei." },
    ],
  },
  {
    slug: "dimostrare-soft-skills-nel-cv",
    title: "Soft skills nel CV: come dimostrarle invece di elencarle",
    excerpt: "\"Ottime capacità comunicative\" scritto in un CV non comunica nulla. Le soft skills si dimostrano con un esempio, non con un aggettivo.",
    category: "CV",
    publishedAt: "2026-06-26",
    readingMinutes: 4,
    content: [
      { type: "p", text: "Una sezione del CV con \"leadership, problem solving, comunicazione\" elencati come parole isolate non convince nessuno: chiunque può scrivere quelle tre parole, indipendentemente da quanto siano vere. Le soft skills, per essere credibili, hanno bisogno di un esempio concreto dentro un'esperienza reale, non di un elenco a parte." },
      { type: "h2", text: "Il problema dell'elenco isolato" },
      { type: "p", text: "Una lista di soft skills senza contesto legge come un compito fatto per riempire uno schema, non come informazione reale su di te. Chi seleziona lo sa, e tende a ignorare quella sezione o a darle pochissimo peso rispetto alle esperienze descritte nei bullet." },
      { type: "h2", text: "Integrarle nei bullet, non isolarle" },
      { type: "p", text: "Invece di scrivere \"ottime capacità di leadership\" in un elenco a parte, un bullet come \"Guidato un team di 5 persone attraverso una riorganizzazione interna, mantenendo la produttività invariata nei primi 3 mesi\" dimostra la leadership senza nominarla mai esplicitamente. Chi legge trae la conclusione da solo, e una conclusione autonoma convince più di un'affermazione diretta." },
      { type: "h2", text: "Le soft skills che contano di più cambiano per ruolo" },
      { type: "p", text: "Non tutte le soft skills pesano uguale per ogni posizione. Per un ruolo di gestione, contano leadership e capacità decisionale. Per un ruolo di supporto clienti, contano pazienza e gestione dello stress. Guarda l'annuncio: spesso indica, tra le righe, quale soft skill specifica sta davvero cercando, più di quanto suggerisca un elenco generico di qualità desiderabili." },
    ],
  },
  {
    slug: "quando-cambiare-lavoro-segnali",
    title: "Quando è il momento giusto di cambiare lavoro: i segnali concreti",
    excerpt: "\"Non mi sento più realizzato\" è vero ma vago. Alcuni segnali più specifici aiutano a capire se è il momento di muoversi davvero.",
    category: "Carriera",
    publishedAt: "2026-07-24",
    readingMinutes: 5,
    content: [
      { type: "p", text: "La sensazione generica di insoddisfazione è un punto di partenza, ma da sola non aiuta a decidere se cambiare lavoro adesso o aspettare. Alcuni segnali più specifici e verificabili rendono la decisione meno basata sull'umore del momento." },
      { type: "h2", text: "Il tuo ruolo è identico a 2 anni fa" },
      { type: "p", text: "Responsabilità, competenze richieste e livello di autonomia sono gli stessi di 24 mesi fa, senza un piano concreto di crescita discusso con il tuo manager. Non è automaticamente un problema se stai ancora imparando molto nel ruolo attuale, ma se anche l'apprendimento si è fermato, la stagnazione è un segnale reale, non un'impressione." },
      { type: "h2", text: "Confronta lo stipendio con il mercato, non con l'anno scorso" },
      { type: "p", text: "Un aumento annuale del 2-3% sembra positivo confrontato con il proprio stipendio precedente, ma può comunque significare restare indietro rispetto al mercato per lo stesso ruolo altrove. Una ricerca periodica (anche solo guardando annunci comparabili) aiuta a capire se il tuo stipendio è ancora allineato, o se sta scivolando indietro senza che te ne accorga." },
      { type: "h2", text: "Il turnover intorno a te è un dato, non un pettegolezzo" },
      { type: "p", text: "Se negli ultimi 12 mesi più colleghi diretti hanno lasciato lo stesso team, per motivi diversi tra loro, è un pattern degno di attenzione, non solo una serie di coincidenze scollegate. Un singolo collega che se ne va per un'offerta migliore è normale. Tre o quattro nello stesso periodo, dallo stesso team, di solito segnalano qualcosa di strutturale." },
      { type: "h2", text: "La domenica sera è diventata un indicatore" },
      { type: "p", text: "Un po' di tensione la domenica sera prima di rientrare al lavoro è comune e non significa nulla di grave da solo. Se quella tensione è diventata costante, intensa, e presente anche nei periodi meno carichi di lavoro, è un segnale che vale la pena prendere sul serio, prima che diventi un problema di salute oltre che di carriera." },
    ],
  },
  {
    slug: "pretesa-salariale-colloquio-senza-svelare-troppo",
    title: "Come rispondere a \"qual è la tua pretesa salariale\" senza svelare troppo presto",
    excerpt: "Rispondere con un numero troppo presto ti toglie margine di trattativa. Rispondere in modo evasivo rischia di sembrare che tu stia nascondendo qualcosa.",
    category: "Colloqui",
    publishedAt: "2026-04-17",
    readingMinutes: 4,
    content: [
      { type: "p", text: "Questa domanda arriva quasi sempre prima che tu sappia davvero cosa comporta il ruolo nel dettaglio, ed è proprio per questo che rispondere con un numero secco è rischioso: se spari troppo basso, è quello il punto da cui parte ogni trattativa successiva; se spari troppo alto senza contesto, rischi di essere scartato prima ancora di arrivare a un'offerta vera." },
      { type: "h2", text: "Il range è meglio del numero secco" },
      { type: "p", text: "\"Sto valutando un range tra X e Y, in base al pacchetto completo e alle responsabilità reali del ruolo\" lascia margine su entrambi i lati senza sembrare evasivo. Il range va costruito su dati di mercato reali per quel ruolo, quella seniority, quella zona geografica, non su una cifra scelta a sensazione." },
      { type: "h2", text: "Rimandare è legittimo, ma va fatto bene" },
      { type: "p", text: "\"Preferirei capire meglio le responsabilità del ruolo prima di darti un numero preciso, ma se ti serve un'indicazione di massima è nell'intorno di X\" è una risposta che rimanda senza sembrare che tu stia evitando la domanda. Un rifiuto secco (\"preferisco non rispondere\") invece, in molti contesti, si legge come mancanza di trasparenza." },
      { type: "h2", text: "Se insistono per un numero preciso" },
      { type: "p", text: "Alcuni recruiter chiedono esplicitamente una cifra unica, non un range. In quel caso, dai il numero più alto del tuo range realistico, non quello più basso: è molto più facile scendere in trattativa da un numero alto che risalire da uno basso una volta che è già stato detto ad alta voce." },
    ],
  },
  {
    slug: "colloquio-telefonico-come-prepararsi",
    title: "Colloquio telefonico: come prepararsi quando non puoi vedere l'interlocutore",
    excerpt: "Senza il volto di chi ascolta, perdi ogni segnale visivo su come sta andando. La preparazione deve compensare quello che il telefono non ti lascia vedere.",
    category: "Colloqui",
    publishedAt: "2026-04-10",
    readingMinutes: 4,
    content: [
      { type: "p", text: "Un colloquio telefonico, spesso il primo filtro prima di un round più approfondito, ha un vincolo che né il colloquio in presenza né quello video hanno: non vedi nessuna reazione. Non sai se chi ti ascolta sta annuendo, se è confuso, se ha già deciso. La preparazione deve compensare quel buio." },
      { type: "h2", text: "Parla più lentamente di quanto ti sembri naturale" },
      { type: "p", text: "Al telefono, senza il supporto visivo delle espressioni facciali, un ritmo normale di conversazione può sembrare frettoloso a chi ascolta. Rallentare leggermente, e fare pause brevi tra un concetto e l'altro, aiuta l'altra persona a seguire senza dover chiedere di ripetere." },
      { type: "h2", text: "Tieni il CV e l'annuncio davanti a te, ma non leggerli" },
      { type: "p", text: "Il vantaggio del telefono è che nessuno vede le tue note. Usale come promemoria di struttura (i punti che vuoi toccare, i numeri che vuoi citare), non come copione da leggere parola per parola: si sente quando qualcuno sta leggendo, anche senza vederlo." },
      { type: "h2", text: "Conferma di aver capito la domanda, non dare per scontato" },
      { type: "p", text: "Senza il linguaggio del corpo, è più facile fraintendere una domanda complessa. Una breve riformulazione (\"Quindi mi stai chiedendo come ho gestito X, giusto?\") prima di rispondere costa due secondi e previene una risposta lunga alla domanda sbagliata." },
      { type: "h2", text: "L'ambiente conta quanto le parole" },
      { type: "p", text: "Un posto silenzioso, senza rumori di fondo imprevedibili (traffico, altre persone, un cane), e un segnale telefonico stabile sono la parte più sottovalutata della preparazione. Un'interruzione tecnica a metà di una risposta articolata costringe a ricominciare, e si perde naturalezza." },
    ],
  },
  {
    slug: "recuperare-un-colloquio-andato-male-a-meta",
    title: "Come gestire un colloquio andato male a metà",
    excerpt: "Una risposta scivolata male non decide da sola l'esito del colloquio. Come reagisci subito dopo, invece, spesso sì.",
    category: "Colloqui",
    publishedAt: "2026-04-03",
    readingMinutes: 4,
    content: [
      { type: "p", text: "Capita a chiunque: una domanda ti coglie impreparato, la risposta esce confusa, e per un attimo pensi che il colloquio sia già compromesso. Nella maggior parte dei casi non lo è: quello che succede nei minuti immediatamente successivi conta più della singola risposta scivolata male." },
      { type: "h2", text: "Non provare a rattoppare in diretta" },
      { type: "p", text: "Il primo istinto è aggiungere subito altre frasi per sistemare quello che è appena uscito male, ma questo spesso peggiora le cose, allungando una risposta già confusa. Meglio chiudere la frase, respirare, e aspettare la domanda successiva con calma reale, non recitata." },
      { type: "h2", text: "Puoi tornarci sopra più avanti, con permesso" },
      { type: "p", text: "Se ti rendi conto qualche minuto dopo che una risposta precedente non ha reso l'idea, è del tutto legittimo dire: \"Posso tornare un attimo sulla domanda di prima? Mi sono reso conto che la mia risposta non ha reso bene il punto.\" Chi fa colloqui apprezza quasi sempre questa onestà più di una risposta imperfetta lasciata così com'è." },
      { type: "h2", text: "Un colloquio è fatto di molti momenti, non di uno solo" },
      { type: "p", text: "Chi seleziona valuta un insieme di risposte, non decide sulla base della peggiore. Una risposta debole in mezzo a diverse risposte solide raramente pesa quanto pensi nel momento in cui succede: il rischio reale è lasciare che quel momento comprometta anche le risposte successive, per il nervosismo che genera." },
    ],
  },
  {
    slug: "domande-trabocchetto-colloquio",
    title: "Domande trabocchetto: le più comuni e come non caderci",
    excerpt: "Alcune domande da colloquio sono progettate per far emergere un'incoerenza. Riconoscerle in anticipo è già metà del lavoro per non caderci.",
    category: "Colloqui",
    publishedAt: "2026-03-27",
    readingMinutes: 5,
    content: [
      { type: "p", text: "Non tutte le domande difficili sono trabocchetti, ma alcune sono costruite proprio per verificare se la tua storia regge sotto pressione, non per informazione genuina. Riconoscerle aiuta a rispondere con calma invece che con difesa." },
      { type: "h2", text: "\"Perché hai cambiato lavoro così spesso?\"" },
      { type: "p", text: "Non è (solo) curiosità: sta verificando se sei affidabile su un impegno di medio termine. La risposta migliore riconosce il pattern se esiste davvero, invece di negarlo, e lo collega a una logica coerente (crescita di ruolo, settori diversi per esplorazione consapevole, non fuga da ogni ambiente difficile)." },
      { type: "h2", text: "\"Cosa dicono di te le persone che non ti apprezzano?\"" },
      { type: "p", text: "Una variante più diretta di \"qual è il tuo difetto\", pensata per far cadere le risposte già preparate. Funziona meglio una risposta specifica e vera (un tratto che genuinamente ha creato attrito con qualcuno, spiegato con contesto) di una difesa generica." },
      { type: "h2", text: "\"Se ti offrissi il lavoro oggi, accetteresti subito?\"" },
      { type: "p", text: "Sta testando il tuo reale livello di interesse, ma una risposta affermativa incondizionata può sembrare disperazione, mentre una eccessivamente cauta può sembrare disinteresse. \"Sì, se le condizioni discusse restano quelle di cui abbiamo parlato\" è una risposta onesta che non chiude né spalanca la porta senza motivo." },
      { type: "h2", text: "Il tratto comune di queste domande" },
      { type: "p", text: "Quasi tutte cercano un'incoerenza tra quello che dici e come lo dici. La difesa migliore non è una risposta perfetta preparata a memoria, ma la coerenza reale tra quello che stai raccontando e quello che hai davvero vissuto: un'incoerenza inventata si nota molto più facilmente di un difetto vero ammesso con calma." },
    ],
  },
  {
    slug: "cv-cambio-settore-senza-esperienza-diretta",
    title: "Come adattare il CV per un cambio di settore senza esperienza diretta",
    excerpt: "Non avere esperienza diretta in un nuovo settore non significa partire da zero. Significa raccontare quello che hai in un linguaggio che il nuovo settore riconosce.",
    category: "CV",
    publishedAt: "2026-03-20",
    readingMinutes: 5,
    content: [
      { type: "p", text: "Un CV che elenca esperienze in un settore diverso da quello a cui ci si candida rischia di essere scartato in pochi secondi, non perché l'esperienza non valga, ma perché il lessico usato non parla la lingua del nuovo settore. Il lavoro da fare non è nascondere da dove vieni, è tradurlo." },
      { type: "h2", text: "Riscrivi i risultati nel linguaggio del settore di destinazione" },
      { type: "p", text: "Se vieni dalla ristorazione e ti candidi per un ruolo di coordinamento operativo, \"gestito un servizio da 80 coperti a sera con 6 persone in sala\" può diventare \"coordinato un team operativo di 6 persone sotto pressione temporale, gestendo priorità in tempo reale\". Il fatto resta identico, il linguaggio cambia per essere riconoscibile a chi legge da fuori quel settore." },
      { type: "h2", text: "Metti in evidenza le competenze trasversali con esempi, non etichette" },
      { type: "p", text: "\"Ottime capacità organizzative\" scritto in astratto non convince nessuno che cambia settore: serve l'esempio concreto che lo dimostra (vedi anche l'articolo su come dimostrare le soft skills nel CV). Chi legge da fuori un settore diverso ha bisogno di più contesto, non di meno, per capire il trasferimento di competenze." },
      { type: "h2", text: "La bio deve dire esplicitamente cosa stai facendo" },
      { type: "p", text: "Un cambio di settore non va nascosto nella speranza che il CV parli da solo: va dichiarato in apertura, con una frase che spiega la direzione (\"Professionista con 6 anni in [settore A], in transizione verso [settore B] per [motivo concreto]\"). Chi legge senza questo contesto rischia di leggere il CV come un errore di candidatura, non come una scelta consapevole." },
    ],
  },
  {
    slug: "cv-neolaureati-senza-esperienza",
    title: "CV per neolaureati senza esperienza lavorativa: cosa scrivere davvero",
    excerpt: "Senza esperienze di lavoro da elencare, il CV sembra vuoto. Il problema non è la mancanza di contenuto, è non sapere dove guardare per trovarlo.",
    category: "CV",
    publishedAt: "2026-03-13",
    readingMinutes: 5,
    content: [
      { type: "p", text: "Chi si affaccia al mercato del lavoro per la prima volta guarda il proprio CV e vede solo un titolo di studio, e conclude che non c'è molto da scrivere. Quasi sempre non è vero: manca solo l'abitudine a riconoscere cosa, in quello che si è già fatto, conta davvero per un recruiter." },
      { type: "h2", text: "La tesi e i progetti universitari sono esperienza, non solo accademia" },
      { type: "p", text: "Un progetto di tesi che ha richiesto raccolta ed elaborazione di dati, un lavoro di gruppo che ha richiesto coordinamento, un'esperienza Erasmus che ha richiesto adattamento a un contesto nuovo: sono tutte esperienze reali, descrivibili con la stessa struttura risultato-azione-contesto usata per un'esperienza lavorativa vera." },
      { type: "h2", text: "Lavori non professionali contano più di quanto si pensi" },
      { type: "p", text: "Cameriere, animatore in un centro estivo, ripetizioni private, gestione dei social di un'associazione universitaria: sono tutti lavori reali che dimostrano affidabilità, gestione della pressione, o competenze specifiche (comunicazione, gestione del tempo, lavoro sotto scadenza). Non vanno omessi solo perché non sembrano allineati al ruolo ambito." },
      { type: "h2", text: "Attività extracurriculari con responsabilità reali" },
      { type: "p", text: "Aver organizzato un evento universitario, gestito il budget di un'associazione studentesca, coordinato un gruppo di volontari: queste esperienze, se descritte con risultati concreti (quante persone coinvolte, quale budget gestito, cosa è stato ottenuto), pesano quanto un'esperienza lavorativa breve." },
      { type: "h2", text: "Meglio poche esperienze ben raccontate che un elenco generico" },
      { type: "p", text: "La tentazione è riempire il CV con tutto quello che si è fatto, elencato in poche parole ciascuna. Funziona meglio il contrario: 3-4 esperienze reali, raccontate con la stessa cura di un bullet lavorativo (cosa hai fatto, con quale risultato), anche se non sono un impiego formale." },
    ],
  },
  {
    slug: "sezione-progetti-senza-esperienza-lunga",
    title: "Come strutturare la sezione progetti se non hai un'esperienza lavorativa lunga",
    excerpt: "Quando il lavoro non basta a riempire il CV, i progetti personali diventano la prova più concreta di quello che sai fare davvero.",
    category: "CV",
    publishedAt: "2026-03-06",
    readingMinutes: 4,
    content: [
      { type: "p", text: "Per chi ha poca esperienza lavorativa formale, o sta cambiando ambito, la sezione progetti può pesare quanto o più della sezione esperienza. Il problema è che spesso viene scritta come un elenco di titoli, invece che come una prova concreta di competenza." },
      { type: "h2", text: "Ogni progetto ha bisogno di un problema, non solo di un risultato" },
      { type: "p", text: "\"Sviluppato un'app per la gestione delle spese personali\" dice cosa è stato fatto, ma non perché conta. \"Sviluppato un'app per la gestione delle spese personali dopo aver notato che le app esistenti non gestivano bene le spese condivise tra coinquilini\" mostra capacità di identificare un problema reale, non solo di seguire un tutorial." },
      { type: "h2", text: "Scegli 2-3 progetti, non un elenco lungo" },
      { type: "p", text: "Un elenco di dieci progetti minori comunica meno di due o tre progetti approfonditi, con un problema, un processo, un risultato, e magari un link a una demo o al codice. La profondità convince più della quantità." },
      { type: "h2", text: "Il link conta quanto la descrizione" },
      { type: "p", text: "Se il progetto è verificabile (un repository pubblico, un sito online, un documento), il link va sempre incluso: trasforma un'affermazione in una prova che chi legge può controllare da solo, se vuole. Un progetto descritto ma non verificabile pesa meno di uno anche piccolo ma reale e visibile." },
    ],
  },
  {
    slug: "cv-cronologico-vs-funzionale",
    title: "Il CV cronologico vs funzionale: quando usare quale",
    excerpt: "Il formato cronologico è lo standard per un motivo preciso. Il formato funzionale esiste per situazioni specifiche, non come alternativa generica.",
    category: "CV",
    publishedAt: "2026-02-27",
    readingMinutes: 4,
    content: [
      { type: "p", text: "Il CV cronologico (esperienze elencate dalla più recente alla più vecchia) è il formato che la maggior parte dei recruiter e degli ATS si aspetta di leggere. Il CV funzionale (organizzato per aree di competenza, non per cronologia) esiste per situazioni specifiche, non come scelta stilistica intercambiabile." },
      { type: "h2", text: "Quando il cronologico è quasi sempre la scelta giusta" },
      { type: "p", text: "Se il tuo percorso è coerente, con una progressione logica di ruoli e responsabilità crescenti, il cronologico mostra esattamente questo, che è un punto di forza. È anche il formato che i sistemi ATS leggono in modo più affidabile, avendo una struttura standard e prevedibile." },
      { type: "h2", text: "Quando il funzionale può avere senso" },
      { type: "p", text: "Un percorso con interruzioni lunghe da spiegare, un cambio di carriera radicale dove la cronologia recente non è rilevante per il ruolo cercato, o esperienze frammentate in molti lavori brevi non collegati tra loro: in questi casi specifici, organizzare per competenze invece che per cronologia può aiutare a mettere in evidenza cosa conta davvero." },
      { type: "h2", text: "Il rischio reale del formato funzionale" },
      { type: "p", text: "Molti recruiter, vedendo un CV funzionale, presumono che ci sia qualcosa da nascondere nella cronologia, anche quando non è così. Un formato ibrido (una breve sezione di competenze in apertura, seguita da un'esperienza comunque cronologica) spesso ottiene lo stesso beneficio senza sollevare questo sospetto." },
    ],
  },
  {
    slug: "job-hopping-piu-lavori-brevi-nel-cv",
    title: "Come gestire più lavori brevi nel CV senza sembrare instabile",
    excerpt: "Diversi lavori brevi in sequenza possono sembrare un problema. La cornice con cui li racconti decide se sembrano instabilità o intraprendenza.",
    category: "CV",
    publishedAt: "2026-02-20",
    readingMinutes: 4,
    content: [
      { type: "p", text: "Una sequenza di lavori durati meno di un anno ciascuno può far scattare un pregiudizio nel recruiter prima ancora di leggere cosa hai fatto in ognuno. Il modo in cui inquadri questa sequenza cambia completamente come viene percepita." },
      { type: "h2", text: "Distingui le cause quando rispondi in colloquio" },
      { type: "p", text: "Un lavoro lasciato per un licenziamento collettivo, uno per un'offerta migliore arrivata prima del previsto, uno per un progetto a termine dichiarato fin dall'inizio: sono situazioni molto diverse tra loro, ma se raccontate tutte con lo stesso tono difensivo, sembrano un'unica narrazione di instabilità." },
      { type: "h2", text: "Nel CV, il contesto aiuta più della giustificazione" },
      { type: "p", text: "Aggiungere una parentesi breve accanto al ruolo (\"contratto a termine di progetto\", \"azienda in ristrutturazione\") toglie l'ambiguità senza bisogno di un paragrafo di spiegazione. Chi legge un CV con più lavori brevi senza alcun contesto tende a presumere il motivo peggiore." },
      { type: "h2", text: "Se il pattern è reale, il colloquio è il posto per affrontarlo direttamente" },
      { type: "p", text: "Se sai che la domanda arriverà, non aspettare che ti colgano di sorpresa: una frase proattiva (\"Ho notato che il mio percorso recente ha diversi cambi ravvicinati, e voglio essere trasparente sul perché\") mostra consapevolezza, che è esattamente quello che rassicura di più chi teme un altro cambio imminente." },
    ],
  },
  {
    slug: "formati-file-ats-pdf-non-sempre-scelta-giusta",
    title: "Formati di file e ATS: perché il PDF non è sempre la scelta giusta",
    excerpt: "Il PDF è quasi sempre la scelta più sicura, ma non è una regola assoluta. Alcuni sistemi di selezione leggono certi formati meglio di altri.",
    category: "ATS",
    publishedAt: "2026-02-13",
    readingMinutes: 4,
    content: [
      { type: "p", text: "Il PDF è il formato più diffuso e generalmente più sicuro per inviare un CV, perché preserva la formattazione indipendentemente dal dispositivo che lo apre. Ma \"generalmente sicuro\" non significa universalmente perfetto: alcuni sistemi di selezione più datati leggono certi PDF peggio di un semplice file Word." },
      { type: "h2", text: "Il problema non è il formato, è come è stato generato" },
      { type: "p", text: "Un PDF creato esportando direttamente da un editor di testo con testo selezionabile viene letto correttamente dalla maggior parte degli ATS. Un PDF creato scansionando un CV stampato, o convertendo un'immagine, contiene solo pixel, non testo: un ATS non può estrarne nulla, ed è come se il CV non esistesse." },
      { type: "h2", text: "Quando l'annuncio specifica un formato, seguilo alla lettera" },
      { type: "p", text: "Se un'azienda chiede esplicitamente un file Word (.docx), inviare un PDF anche ben fatto può comunque penalizzarti: alcuni sistemi interni sono configurati per leggere in modo ottimale solo il formato richiesto. La richiesta esplicita dell'azienda batte sempre la convenzione generale." },
      { type: "h2", text: "Il test rapido prima di inviare qualsiasi formato" },
      { type: "p", text: "Prima di inviare il CV, prova a selezionare tutto il testo del file e incollarlo in un editor semplice. Se il testo esce leggibile e nell'ordine giusto, il file è probabilmente leggibile anche da un ATS. Se esce come un'immagine non selezionabile, o mescolato, è un problema da correggere prima di inviarlo, qualunque sia il formato." },
    ],
  },
  {
    slug: "acronimi-abbreviazioni-cv-rischio-ats",
    title: "Acronimi e abbreviazioni nel CV: quando sono un rischio per l'ATS",
    excerpt: "Un acronimo che tu conosci a memoria potrebbe non essere quello che un sistema di filtraggio riconosce come corrispondenza con l'annuncio.",
    category: "ATS",
    publishedAt: "2026-02-06",
    readingMinutes: 3,
    content: [
      { type: "p", text: "Scrivere \"PM\" invece di \"Project Manager\", o \"CRM\" senza mai scrivere per esteso \"Customer Relationship Management\", sembra normale a chi lavora ogni giorno in quel settore. Per un sistema di filtraggio automatico che cerca corrispondenze testuali con le parole chiave dell'annuncio, però, l'acronimo e la forma estesa possono non essere riconosciuti come equivalenti." },
      { type: "h2", text: "La soluzione più sicura: scrivere entrambe le forme" },
      { type: "p", text: "\"Project Manager (PM)\" alla prima occorrenza copre sia chi cerca la forma estesa sia chi cerca l'acronimo, in un sistema automatico o in una lettura umana veloce. Non serve farlo per ogni singola occorrenza nel documento, basta la prima volta che il termine compare." },
      { type: "h2", text: "Gli acronimi specifici dell'azienda precedente non aiutano nessuno" },
      { type: "p", text: "Alcuni acronimi sono interni a una specifica azienda o settore molto verticale, e senza spiegazione risultano incomprensibili sia a un ATS sia a un recruiter che non viene dallo stesso contesto specifico. Se un acronimo non è di uso comune e riconoscibile nel settore in generale, va sciolto per esteso sempre." },
      { type: "h2", text: "Controlla gli acronimi usati nell'annuncio stesso" },
      { type: "p", text: "Se l'annuncio usa una forma specifica (es. \"SEO\" invece di \"Search Engine Optimization\"), allineare il tuo CV a quella stessa forma aumenta le probabilità di un matching testuale corretto, più che scegliere arbitrariamente una delle due versioni." },
    ],
  },
  {
    slug: "come-capire-se-azienda-usa-ats",
    title: "Come capire se un'azienda usa davvero un ATS (e quanto conta)",
    excerpt: "Non tutte le aziende filtrano le candidature con un software. Sapere quando è probabile aiuta a decidere quanto tempo investire nell'ottimizzazione.",
    category: "ATS",
    publishedAt: "2025-12-26",
    readingMinutes: 4,
    content: [
      { type: "p", text: "L'ottimizzazione per gli ATS ha senso soprattutto quando c'è davvero un ATS a leggere la candidatura prima di un umano. Piccole aziende con selezione diretta da parte del titolare, o candidature inviate come contatto diretto a una persona specifica, spesso saltano questo filtro del tutto." },
      { type: "h2", text: "Segnali che un'azienda probabilmente usa un ATS" },
      { type: "ul", items: [
        "La candidatura avviene tramite un portale dedicato, non una semplice email",
        "Il portale chiede di compilare campi separati (esperienza, istruzione) oltre a caricare il CV",
        "L'azienda ha più di circa 100 dipendenti o un reparto HR strutturato",
        "L'annuncio è pubblicato su più piattaforme contemporaneamente con lo stesso formato",
      ] },
      { type: "h2", text: "Quando l'ottimizzazione ATS conta meno" },
      { type: "p", text: "Per una candidatura diretta via email a un piccolo studio professionale, o attraverso un contatto personale/referral interno, il documento verrà probabilmente letto direttamente da una persona. In questi casi, un CV leggibile e ben scritto conta più della struttura tecnica ottimizzata per un parser." },
      { type: "h2", text: "La strategia più sicura resta comunque unica" },
      { type: "p", text: "Un CV a colonna singola, con struttura chiara e testo selezionabile, funziona bene sia che venga letto da un ATS sia che venga letto direttamente da una persona: non c'è un compromesso reale tra le due cose. Il dubbio se un'azienda usi o meno un ATS non dovrebbe quindi cambiare come strutturi il documento, solo quanto tempo dedichi a scegliere le parole chiave esatte." },
    ],
  },
  {
    slug: "chiedere-raccomandazione-linkedin",
    title: "Come chiedere una raccomandazione su LinkedIn senza sembrare invadente",
    excerpt: "Una richiesta generica ottiene quasi sempre una raccomandazione generica. Più la richiesta è specifica, più la risposta è utile davvero.",
    category: "LinkedIn",
    publishedAt: "2025-12-19",
    readingMinutes: 3,
    content: [
      { type: "p", text: "Il pulsante \"Richiedi una raccomandazione\" di LinkedIn invia un messaggio standard che, lasciato così com'è, produce quasi sempre una raccomandazione altrettanto generica: due righe cortesi che non dicono nulla di specifico su di te." },
      { type: "h2", text: "Personalizza sempre il messaggio, mai il default" },
      { type: "p", text: "Scrivi un messaggio breve che ricorda un contesto preciso condiviso (\"Mi farebbe piacere una tua raccomandazione sul progetto X che abbiamo seguito insieme, magari menzionando come abbiamo gestito la scadenza stretta\"). Dare un punto di partenza concreto rende più facile per l'altra persona scrivere qualcosa di specifico, invece di lasciarla di fronte a una pagina vuota." },
      { type: "h2", text: "Chiedi alla persona giusta per il contesto giusto" },
      { type: "p", text: "Un ex manager diretto può parlare di leadership e affidabilità; un collega dello stesso livello può parlare di collaborazione quotidiana; un cliente può parlare di risultati concreti ottenuti per lui. Chiedere sempre alla stessa persona, o solo a chi occupa una posizione senior, produce raccomandazioni tutte simili tra loro." },
      { type: "h2", text: "Ricambia, se puoi farlo onestamente" },
      { type: "p", text: "Offrire di scrivere a tua volta una raccomandazione per chi te la scrive (solo se puoi farlo con sincerità) rende la richiesta uno scambio naturale, non un favore a senso unico. Non scrivere mai una raccomandazione che non pensi davvero solo per reciprocità: si nota, e vale meno per entrambi." },
    ],
  },
  {
    slug: "quando-attivare-open-to-work-linkedin",
    title: "Il momento giusto per aggiornare il proprio stato \"Open to Work\"",
    excerpt: "Attivarlo troppo presto può creare tensioni con il datore attuale. Non attivarlo mai può far perdere occasioni che passano solo di lì.",
    category: "LinkedIn",
    publishedAt: "2025-12-12",
    readingMinutes: 4,
    content: [
      { type: "p", text: "La funzione \"Open to Work\" di LinkedIn (la cornice verde sulla foto profilo, o la versione visibile solo ai recruiter) genera spesso un dubbio: attivarla può sembrare un segnale di insoddisfazione al proprio datore di lavoro attuale, se colleghi o superiori la notano." },
      { type: "h2", text: "La versione visibile solo ai recruiter è quasi sempre la scelta più sicura" },
      { type: "p", text: "LinkedIn offre un'opzione che mostra la cornice verde pubblicamente a tutti, e una versione che la rende visibile solo ai recruiter che usano gli strumenti di reclutamento della piattaforma, invisibile a colleghi e al proprio datore di lavoro attuale. Nella maggior parte dei casi, quest'ultima è sufficiente per aumentare la visibilità senza rischi." },
      { type: "h2", text: "Quando attivarla anche pubblicamente" },
      { type: "p", text: "Se sei già senza lavoro, o se il tuo attuale datore è già a conoscenza della tua ricerca (es. dopo un annuncio di licenziamento collettivo), la versione pubblica ha senso: aumenta ulteriormente la visibilità senza nulla da nascondere." },
      { type: "h2", text: "Non è solo un interruttore, è un segnale che va supportato" },
      { type: "p", text: "Attivare \"Open to Work\" senza aggiornare anche l'headline, il riepilogo e le competenze del profilo (vedi l'articolo su come ottimizzare il profilo LinkedIn) sfrutta solo una parte del potenziale. Il segnale attira l'attenzione, ma è il resto del profilo a convincere chi la nota a scriverti davvero." },
    ],
  },
  {
    slug: "usare-linkedin-per-ricerche-prima-del-colloquio",
    title: "Come usare LinkedIn per fare ricerche sull'azienda prima di un colloquio",
    excerpt: "Il profilo aziendale e quello di chi ti intervista contengono più informazioni utili di quanto sembri, se sai cosa cercare.",
    category: "LinkedIn",
    publishedAt: "2025-12-05",
    readingMinutes: 4,
    content: [
      { type: "p", text: "Prima di un colloquio, molte persone leggono solo il sito dell'azienda. LinkedIn contiene informazioni che il sito ufficiale non mostra mai: la composizione reale del team, i movimenti recenti di personale, e a volte il percorso professionale di chi ti intervisterà." },
      { type: "h2", text: "Guarda chi lavora davvero nel team che ti interessa" },
      { type: "p", text: "Cercando i dipendenti dell'azienda con un ruolo simile a quello per cui ti candidi, puoi capire il livello di seniority reale del team, da quanto tempo ci lavorano in media (un indicatore indiretto di turnover), e da dove provengono professionalmente." },
      { type: "h2", text: "Il profilo di chi ti intervista è un contesto utile, non un'arma" },
      { type: "p", text: "Sapere che chi ti intervista viene dallo stesso settore da cui vieni tu, o ha in comune un'esperienza specifica, può aiutarti a costruire un rapporto più naturale nella conversazione. Non è invece opportuno menzionare dettagli troppo personali trovati sul profilo: la ricerca serve a te per prepararti, non per dimostrare quanto hai scavato." },
      { type: "h2", text: "Movimenti recenti raccontano una storia" },
      { type: "p", text: "Diverse assunzioni recenti nello stesso team possono indicare crescita; diverse uscite ravvicinate possono indicare un problema. Nessuno dei due segnali è definitivo da solo, ma insieme alle altre informazioni raccolte aiutano a farsi un'idea più completa prima ancora di entrare nella stanza." },
    ],
  },
  {
    slug: "troppa-attivita-linkedin-puo-ritorcersi-contro",
    title: "Perché troppa attività su LinkedIn può ritorcersi contro di te",
    excerpt: "Pubblicare spesso non è automaticamente un vantaggio. Il contenuto e il contesto contano più della frequenza.",
    category: "LinkedIn",
    publishedAt: "2026-01-30",
    readingMinutes: 4,
    content: [
      { type: "p", text: "Il consiglio di \"essere attivi su LinkedIn\" viene spesso frainteso come \"pubblicare il più possibile\". Un'attività eccessiva, soprattutto se il contenuto è ripetitivo o percepito come autopromozionale, può generare l'effetto opposto a quello desiderato." },
      { type: "h2", text: "Il contenuto che sembra costruito ad arte non convince" },
      { type: "p", text: "Post con una formula riconoscibile (un aneddoto personale seguito da una lezione di vita generica, ripetuto ogni pochi giorni) tende a essere identificato rapidamente come contenuto costruito per l'algoritmo, non come condivisione genuina. Chi legge nota lo schema, anche senza saperlo articolare." },
      { type: "h2", text: "Un datore di lavoro attuale può notare troppa attività esterna" },
      { type: "p", text: "Se sei ancora impiegato e pubblichi contenuti molto frequenti su temi professionali generali, un manager attento potrebbe percepirlo come tempo ed energia dirottati altrove, anche se il contenuto è pubblicato fuori orario di lavoro. Non è una regola assoluta, ma vale la pena esserne consapevoli." },
      { type: "h2", text: "La qualità di poche interazioni batte il volume" },
      { type: "p", text: "Un commento genuino e specifico su un post di qualcun altro nel tuo settore costruisce più relazione reale di un post proprio pubblicato ogni giorno. La visibilità utile per la ricerca di lavoro viene più spesso da conversazioni reali che dal volume di pubblicazioni personali." },
    ],
  },
  {
    slug: "chiedere-un-aumento-senza-revisione-annuale",
    title: "Come chiedere un aumento senza aspettare la revisione annuale",
    excerpt: "Aspettare il ciclo di revisione annuale non è sempre necessario. Se la motivazione è concreta, il momento giusto può essere prima.",
    category: "Carriera",
    publishedAt: "2026-01-23",
    readingMinutes: 5,
    content: [
      { type: "p", text: "L'idea che un aumento si possa chiedere solo durante la revisione annuale è una convenzione, non una regola fissa in ogni azienda. Se hai una motivazione concreta e recente, aspettare mesi solo per rispettare un calendario può significare accettare una sottovalutazione più a lungo del necessario." },
      { type: "h2", text: "I momenti in cui una richiesta fuori ciclo ha più forza" },
      { type: "ul", items: [
        "Hai assunto responsabilità significativamente maggiori rispetto a quando è stato fissato il tuo stipendio attuale",
        "Hai ricevuto un'offerta concreta da un'altra azienda che vuoi usare come leva reale, non come bluff",
        "Un risultato misurabile e recente (un progetto concluso con successo, un obiettivo superato) rende il momento naturale",
      ] },
      { type: "h2", text: "Come strutturare la richiesta" },
      { type: "p", text: "Chiedi un incontro dedicato, non improvvisare la conversazione a margine di un'altra riunione. Porta dati concreti (responsabilità aggiunte, risultati ottenuti, dati di mercato per ruoli comparabili), non solo la sensazione soggettiva di meritarlo." },
      { type: "h2", text: "Prepara anche una risposta a un rifiuto" },
      { type: "p", text: "Non tutte le richieste fuori ciclo vengono accolte, anche quando la motivazione è solida: alcuni budget sono davvero bloccati fino al ciclo successivo. Chiedere esplicitamente cosa servirebbe perché la richiesta venga accolta la prossima volta trasforma un rifiuto in un percorso concreto, invece che in un vicolo cieco." },
    ],
  },
  {
    slug: "mentor-e-sponsor-differenza-per-la-carriera",
    title: "Mentor e sponsor: la differenza che conta per la tua carriera",
    excerpt: "Un mentor ti dà consigli. Uno sponsor spende la propria credibilità per farti avanzare quando non sei nella stanza. Sono due cose diverse.",
    category: "Carriera",
    publishedAt: "2026-01-16",
    readingMinutes: 4,
    content: [
      { type: "p", text: "I due termini vengono spesso usati come sinonimi, ma descrivono ruoli molto diversi nella crescita di una carriera. Un mentor ti offre consigli, prospettiva ed esperienza, in genere in conversazioni dirette con te. Uno sponsor fa qualcosa di diverso: usa la propria influenza per farti avanzare quando tu non sei presente." },
      { type: "h2", text: "Il mentor ti aiuta a crescere, lo sponsor ti apre le porte" },
      { type: "p", text: "Un mentor può aiutarti a capire come migliorare una presentazione, o come gestire un conflitto con un collega. Uno sponsor è la persona che, in una riunione a cui tu non partecipi, dice \"dovremmo considerare [il tuo nome] per questo progetto\" — un'azione che nessun mentor, per quanto generoso di consigli, può replicare senza avere anche influenza reale nell'organizzazione." },
      { type: "h2", text: "Molte persone hanno mentor, poche hanno sponsor" },
      { type: "p", text: "È relativamente facile trovare qualcuno disposto a dare consigli in una conversazione informale. È molto più raro costruire un rapporto abbastanza solido perché qualcuno metta la propria credibilità in gioco per te in una stanza dove tu non ci sei. Questo secondo tipo di rapporto si costruisce con risultati visibili nel tempo, non con una singola richiesta diretta." },
      { type: "h2", text: "Come costruire, senza chiederlo esplicitamente" },
      { type: "p", text: "Non si chiede a qualcuno \"vuoi essere il mio sponsor\", è una richiesta che suona artificiale e mette l'altra persona in imbarazzo. Si costruisce facendo un lavoro visibile e affidabile sotto gli occhi di persone con influenza reale, e lasciando che la fiducia si formi nel tempo attraverso i risultati, non attraverso la richiesta diretta." },
    ],
  },
  {
    slug: "gestire-un-capo-che-non-delega",
    title: "Come gestire un capo che non delega",
    excerpt: "Un manager che controlla ogni dettaglio spesso non lo fa per sfiducia generica, ma per una ragione specifica che si può affrontare.",
    category: "Carriera",
    publishedAt: "2026-01-09",
    readingMinutes: 5,
    content: [
      { type: "p", text: "Un manager che rivede ogni singolo dettaglio del tuo lavoro, anche su compiti che dovresti gestire in autonomia, è una delle fonti di frustrazione più comuni sul lavoro. La reazione istintiva è vederlo come un problema di fiducia generica, ma spesso c'è una causa più specifica e affrontabile." },
      { type: "h2", text: "Capire la causa prima di reagire" },
      { type: "p", text: "Un capo che non delega può farlo per motivi molto diversi: è stato scottato in passato da un errore costoso di qualcun altro, è sotto pressione lui stesso da chi sta sopra di lui, non ha ancora avuto prove sufficienti delle tue capacità su quel tipo specifico di compito, o semplicemente non ha mai imparato a delegare con nessuno, non solo con te." },
      { type: "h2", text: "Costruisci fiducia con piccoli passi verificabili" },
      { type: "p", text: "Invece di chiedere direttamente più autonomia in generale, proponi di gestire in autonomia un compito piccolo e ben definito, con un aggiornamento concordato a metà percorso. Un piccolo successo verificabile costruisce più fiducia di una richiesta astratta di \"più fiducia\"." },
      { type: "h2", text: "Una conversazione diretta, ma sui fatti non sulle sensazioni" },
      { type: "p", text: "\"Mi sento controllato\" è una frase che mette sulla difensiva. \"Ho notato che rivediamo insieme anche i dettagli di X: cosa ti aiuterebbe a sentirti più tranquillo nel lasciarmi gestire quella parte in autonomia?\" apre una conversazione pratica invece di una discussione emotiva." },
    ],
  },
  {
    slug: "ricominciare-dopo-un-licenziamento-primi-30-giorni",
    title: "Ricominciare da zero dopo un licenziamento: i primi 30 giorni",
    excerpt: "I primi trenta giorni dopo un licenziamento decidono più di quanto sembri quanto durerà davvero la ricerca del prossimo lavoro.",
    category: "Carriera",
    publishedAt: "2026-01-02",
    readingMinutes: 5,
    content: [
      { type: "p", text: "Un licenziamento, atteso o improvviso, mette alla prova prima di tutto la gestione del tempo e dell'energia, prima ancora delle competenze di ricerca del lavoro vere e proprie. Come vengono usati i primi trenta giorni influisce concretamente sulla durata di tutto il periodo successivo." },
      { type: "h2", text: "I primi giorni: sistemare, non cercare ancora" },
      { type: "p", text: "Nella prima settimana ha senso occuparsi delle cose pratiche (disoccupazione, eventuale liquidazione, budget personale per i mesi successivi) prima ancora di lanciarsi nella ricerca attiva. Candidarsi in stato di ansia acuta produce quasi sempre candidature peggiori di quelle inviate con un minimo di lucidità recuperata." },
      { type: "h2", text: "Aggiorna gli strumenti prima di usarli" },
      { type: "p", text: "CV, profilo LinkedIn e un elenco di referenze pronte vanno aggiornati prima di iniziare a candidarsi in massa, non durante. Una prima ondata di candidature con materiali non aggiornati spreca spesso le occasioni migliori, quelle che arrivano proprio nelle prime settimane quando la rete di contatti è ancora informata della situazione." },
      { type: "h2", text: "Riattiva la rete con un messaggio onesto, non generico" },
      { type: "p", text: "Un messaggio diretto a contatti fidati (\"Sto cercando un nuovo ruolo in [ambito], se ti viene in mente qualcosa o qualcuno mi farebbe piacere un confronto\") funziona meglio di un post generico pubblico, e attiva più spesso occasioni reali attraverso la rete di secondo livello (i contatti dei tuoi contatti)." },
      { type: "h2", text: "Una routine giornaliera protegge più della sola ricerca attiva" },
      { type: "p", text: "Mantenere una struttura quotidiana (orari fissi, obiettivi giornalieri piccoli e realistici, tempo dedicato anche ad attività non legate alla ricerca) protegge dal logoramento psicologico di una ricerca che, in molti casi, dura più a lungo di quanto si speri all'inizio." },
    ],
  },
];

export function getBlogPost(slug: string): BlogPost | undefined {
  return BLOG_POSTS.find((p) => p.slug === slug);
}
