import { logClaudeUsage } from "./log-claude-usage";

// Researches the hiring company behind a job posting (via Claude's
// server-side web_search + web_fetch tools) and returns a compact,
// interview-prep report: what the company does, its market, culture,
// recent news, and the JD's own critical points — each backed by a real
// source URL Claude actually visited. Deliberately does NOT touch the
// user's CV at all (see the product spec this was built from) — this makes
// the feature usable both from a signed-in account and, later, from an
// anonymous visitor who hasn't uploaded a CV yet.

export interface InterviewPrepSource {
  title: string;
  url: string;
}

export interface InterviewPrepContent {
  company_name: string | null;
  role_title: string | null;
  company_summary: string;
  market: string;
  culture_values: string;
  recent_news: string[];
  role_focus_points: string[];
  likely_questions: string[];
  sources: InterviewPrepSource[];
  // One of LANGUAGE_NAMES's keys below — set programmatically from the
  // caller's requested language, not trusted to the model (see
  // generateInterviewPrep).
  language: string;
}

// Haiku 4.5 was tried here for cost (~$0.06-0.07/report vs ~$0.15-0.35 on
// Sonnet) but proved meaningfully less reliable at this specific task: it
// regularly lost or misfiled content across recent_news/role_focus_points/
// likely_questions even with the coerceStringArray recovery below in place
// (never crashes, but sections come back thinner or empty more often).
// Kept on Sonnet 5 after comparing real output side by side — the user
// chose consistency over the cost saving for this feature.
const MODEL = "claude-sonnet-5";

// Same 7 languages offered by components/translate-cv-button.tsx's
// TRANSLATE_LANGUAGES — kept as a separate map here (English names, for the
// prompt) rather than importing that client component into server code.
const LANGUAGE_NAMES: Record<string, string> = {
  it: "Italian",
  en: "English",
  es: "Spanish",
  fr: "French",
  de: "German",
  pt: "Portuguese",
  zh: "Simplified Chinese",
};

// The report's own prose is quote-heavy by nature (quoting a company's
// mission statement, a culture tagline, a news headline) — asking Claude to
// hand-type that as a raw JSON string reliably produced unescaped quotes
// that broke JSON.parse in production (two distinct malformed-JSON bugs in
// a row, see git history). A tool_use input is generated by the API's own
// constrained JSON encoder, not hand-typed text, so this class of bug can't
// happen — Claude calls this tool once, as its last action, instead of
// writing the report as a text block.
const SUBMIT_TOOL_NAME = "submit_interview_report";

const SUBMIT_TOOL = {
  name: SUBMIT_TOOL_NAME,
  description: "Submit the completed interview-prep report. Call this exactly once, as your final action, after you've finished researching the company — never write the report as plain text instead.",
  input_schema: {
    type: "object",
    properties: {
      company_name: { type: ["string", "null"], description: "The hiring company's name, or null if the posting doesn't identify one." },
      role_title: { type: ["string", "null"], description: "The job title from the posting, or null if unclear." },
      company_summary: { type: "string", description: "2-4 sentences: what the company does, its size, products/services, mission." },
      market: { type: "string", description: "2-4 sentences: the market/sector and the company's position in it." },
      culture_values: { type: "string", description: "2-4 sentences: the company's culture and values, from real sources." },
      recent_news: { type: "array", items: { type: "string" }, description: "2-5 concrete, dated recent news items — empty array if nothing genuinely recent was found." },
      role_focus_points: { type: "array", items: { type: "string" }, description: "Concrete points from the job posting itself worth remembering for the interview." },
      likely_questions: { type: "array", items: { type: "string" }, description: "Plausible interview questions grounded in the posting and company profile." },
      // A flat array of strings, not objects — an array of {title, url}
      // objects made the model's tool call occasionally serialize this one
      // field as broken pseudo-XML instead of real JSON (a nested-object
      // array schema quirk observed in production). generateInterviewPrep
      // below parses each "Title — https://url" line back into
      // {title, url} for the caller.
      sources: {
        type: "array",
        items: { type: "string" },
        description: "Every source actually fetched or searched, each as one string: \"Title — https://full-url\". Never a URL that wasn't genuinely visited via the tools.",
      },
    },
    required: ["company_name", "role_title", "company_summary", "market", "culture_values", "recent_news", "role_focus_points", "likely_questions", "sources"],
  },
};

function buildSystemPrompt(languageName: string): string {
  return `You help a job candidate prepare for an interview by researching the hiring company behind a job posting and summarizing what they need to know before walking in. You will be given the job posting as plain text. Use the web_search and web_fetch tools to research the company using real, current, public sources (the company's own website, its LinkedIn page, recent press coverage) — never rely on prior knowledge alone for anything that could be outdated (team size, products, leadership, recent moves).

WHAT TO PRODUCE (all from real sources you actually searched/fetched, never invented):
- The company's name and the role title, read from the job posting itself. If the job posting is anonymized or a generic listing with no identifiable company, set company_name to null and say so plainly in company_summary rather than guessing.
- A summary of what the company does, roughly how large it is, its main products/services, and its stated mission — relevant to make a genuine, informed conversation, not a marketing blurb.
- The market/sector it operates in and its general position there (competitors, niche, growth stage) if genuinely findable.
- Its culture and values, drawn from its own careers page, About page, or LinkedIn — not invented generic corporate language.
- 2-5 concrete, recent, dated news items or public moves (funding, launches, expansions, leadership changes) — an empty list if you can't find anything genuinely recent and specific, rather than padding it with generic facts.
- role_focus_points: concrete, specific things from the JOB POSTING TEXT itself worth keeping in mind for the interview — critical requirements, unusual aspects of the role, anything a candidate could easily overlook on a first read.
- likely_questions: plausible interview questions this specific posting and company profile suggest, grounded in what the posting actually asks for (not generic "tell me about yourself" filler).
- sources: every URL you actually fetched or that a cited fact came from, each formatted as one string "Title — https://full-url". Only include URLs you genuinely visited via the tools — never list a URL you didn't actually use.

RULES:
- Never fabricate a fact, statistic, or news item. If you can't verify something with the tools, leave it out rather than guessing.
- Keep every field concise — the final output becomes a 1-2 page PDF the candidate skims right before the interview, not a research dossier. company_summary, market, and culture_values should each be 2-4 sentences at most. Each item in recent_news/role_focus_points/likely_questions should be one sentence.
- Write every field as clean, plain prose — no citation markers, footnote numbers, bracketed references, or tags of any kind (e.g. never write something like "<cite index=...>" or "[3]") inside company_summary, market, culture_values, or any other field. All source attribution belongs only in the sources field.
- Do not write any commentary, preamble, or explanation of your research process in your visible text.

LANGUAGE: write every text field in ${languageName}, regardless of the language the job posting itself is written in — the candidate chose ${languageName} explicitly for this report.

When you have finished researching, call the ${SUBMIT_TOOL_NAME} tool exactly once with the complete report. That tool call is the only way to deliver your result — do not write the report as a text message.`;
}

interface ClaudeContentBlock {
  type: string;
  text?: string;
  name?: string;
  input?: unknown;
  [key: string]: unknown;
}

interface ClaudeToolResponse {
  stop_reason: string;
  content: ClaudeContentBlock[];
  usage?: { input_tokens: number; output_tokens: number; cache_creation_input_tokens?: number; cache_read_input_tokens?: number };
}

async function callClaude(messages: unknown[], systemPrompt: string): Promise<ClaudeToolResponse> {
  const res = await fetch("https://api.anthropic.com/v1/messages", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "x-api-key": process.env.ANTHROPIC_API_KEY!,
      "anthropic-version": "2023-06-01",
    },
    body: JSON.stringify({
      model: MODEL,
      // Extra headroom over a plain report's needs — "sources" is both the
      // last field the model writes and structurally a list, and the two
      // production failures so far both involved a long, research-heavy
      // job posting where that final field came back malformed. More
      // budget can't hurt and may reduce end-of-response pressure.
      max_tokens: 12000,
      system: [{ type: "text", text: systemPrompt, cache_control: { type: "ephemeral" } }],
      output_config: { effort: "high" },
      tools: [
        { type: "web_search_20250305", name: "web_search", max_uses: 4 },
        { type: "web_fetch_20250910", name: "web_fetch", max_uses: 3 },
        SUBMIT_TOOL,
      ],
      messages,
    }),
  });

  if (!res.ok) {
    const body = await res.text();
    throw new Error(`Anthropic API error ${res.status}: ${body}`);
  }
  return res.json() as Promise<ClaudeToolResponse>;
}

// Shape as it comes straight off the tool call — "sources" is still the
// flat "Title — https://url" strings described on SUBMIT_TOOL, not yet
// split into {title, url}.
type SubmittedReport = Omit<InterviewPrepContent, "language" | "sources"> & { sources: string[] };

// The report arrives as this tool's already-parsed `input` object — no
// JSON.parse, no risk of a stray unescaped quote in the model's prose
// breaking extraction (see SUBMIT_TOOL's own comment for why this replaced
// the earlier free-text JSON approach).
function extractSubmittedReport(content: ClaudeContentBlock[]): SubmittedReport {
  const toolUse = content.find((b) => b.type === "tool_use" && b.name === SUBMIT_TOOL_NAME);
  if (!toolUse) {
    throw new Error("The model finished without submitting a report.");
  }
  return toolUse.input as SubmittedReport;
}

// Splits one "Title — https://full-url" line back into {title, url} — finds
// the first URL-shaped substring and treats everything before it (minus a
// trailing dash/colon separator) as the title. Falls back to using the
// whole line as the title with an empty url if the model didn't include one.
function parseSourceLine(line: string): InterviewPrepSource {
  const urlMatch = line.match(/https?:\/\/\S+/);
  if (!urlMatch || urlMatch.index === undefined) {
    return { title: line.trim(), url: "" };
  }
  const url = urlMatch[0].replace(/[),.]+$/, "");
  const title = line.slice(0, urlMatch.index).replace(/[-–—:]\s*$/, "").trim();
  return { title: title || url, url };
}

// Defends against a model occasionally returning an array field as a plain
// string instead of a real array — observed on Haiku 4.5, which sometimes
// wraps a bullet list in stray pseudo-XML (e.g. "<![CDATA[\n- item\n- item\n]]>")
// instead of the schema's actual array type. Recovers what it can: strips
// CDATA/tag wrapper artifacts, splits on newlines, and treats each non-empty
// line as one item — good enough to salvage a bulleted list. Returns an
// empty array (never throws) if the value is unusable in any other shape.
function coerceStringArray(value: unknown): string[] {
  if (Array.isArray(value)) return value.filter((v): v is string => typeof v === "string");
  if (typeof value !== "string") return [];
  return value
    .replace(/<!\[CDATA\[/gi, "")
    .replace(/\]\]>/g, "")
    .replace(/<\/?[a-z][^>]*>/gi, "")
    .split("\n")
    .map((line) => line.replace(/^[\s\-•*]+/, "").trim())
    .filter(Boolean);
}

const MAX_CONTINUATIONS = 4;

export async function generateInterviewPrep(
  jobPostingText: string,
  language: string,
  userId?: string | null
): Promise<InterviewPrepContent> {
  const languageName = LANGUAGE_NAMES[language] ?? LANGUAGE_NAMES.it;
  const systemPrompt = buildSystemPrompt(languageName);
  const messages: unknown[] = [
    {
      role: "user",
      content: `<job_posting>\n${jobPostingText}\n</job_posting>\n\nResearch the hiring company, then call ${SUBMIT_TOOL_NAME} with the completed report.`,
    },
  ];

  let response = await callClaude(messages, systemPrompt);
  logClaudeUsage("interview_prep", MODEL, response.usage, userId);

  // Calling our own client tool ends the turn with stop_reason "tool_use" —
  // that's the success path, handled below. "pause_turn" is different: the
  // server-tool loop (web_search/web_fetch) hit its own internal iteration
  // cap before Claude was done researching — resend the paused assistant
  // turn unchanged to let the API pick back up, per Anthropic's documented
  // pause_turn continuation pattern.
  let continuations = 0;
  while (response.stop_reason === "pause_turn" && continuations < MAX_CONTINUATIONS) {
    messages.push({ role: "assistant", content: response.content });
    response = await callClaude(messages, systemPrompt);
    logClaudeUsage("interview_prep", MODEL, response.usage, userId);
    continuations++;
  }

  if (response.stop_reason === "refusal") {
    throw new Error("The model declined to research this job posting.");
  }
  if (response.stop_reason === "max_tokens") {
    throw new Error("The report was too long to finish generating — please try again.");
  }

  const submitted = extractSubmittedReport(response.content);
  if (process.env.DEBUG_INTERVIEW_PREP) {
    console.error("[interview-prep debug] raw submitted:", JSON.stringify(submitted));
  }
  return {
    ...submitted,
    recent_news: coerceStringArray(submitted.recent_news),
    role_focus_points: coerceStringArray(submitted.role_focus_points),
    likely_questions: coerceStringArray(submitted.likely_questions),
    sources: coerceStringArray(submitted.sources).map(parseSourceLine),
    // Set from the caller's explicit choice rather than trusted to the
    // model's own output.
    language,
  };
}
